//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tway/dev/FeedRead/core/src/main/java/com/example/data/HttpUtil.java
//

#ifndef _ComExampleDataHttpUtil_H_
#define _ComExampleDataHttpUtil_H_

#include "J2ObjC_header.h"

@interface ComExampleDataHttpUtil : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)toStringWithNSString:(NSString *)urlString;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleDataHttpUtil)

FOUNDATION_EXPORT NSString *ComExampleDataHttpUtil_toStringWithNSString_(NSString *urlString);

FOUNDATION_EXPORT void ComExampleDataHttpUtil_init(ComExampleDataHttpUtil *self);

FOUNDATION_EXPORT ComExampleDataHttpUtil *new_ComExampleDataHttpUtil_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComExampleDataHttpUtil)

#endif // _ComExampleDataHttpUtil_H_
