//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/annotations/SerializedName.java
//

#ifndef _ComGoogleGsonAnnotationsSerializedName_H_
#define _ComGoogleGsonAnnotationsSerializedName_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComGoogleGsonAnnotationsSerializedName < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

@end

@interface ComGoogleGsonAnnotationsSerializedName : NSObject < ComGoogleGsonAnnotationsSerializedName > {
 @private
  NSString *value_;
}

- (instancetype)initWithValue:(NSString *)value__;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsSerializedName)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsSerializedName)

#endif // _ComGoogleGsonAnnotationsSerializedName_H_
