//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/annotations/Until.java
//

#ifndef _ComGoogleGsonAnnotationsUntil_H_
#define _ComGoogleGsonAnnotationsUntil_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComGoogleGsonAnnotationsUntil < JavaLangAnnotationAnnotation >

@property (readonly) jdouble value;

@end

@interface ComGoogleGsonAnnotationsUntil : NSObject < ComGoogleGsonAnnotationsUntil > {
 @private
  jdouble value_;
}

- (instancetype)initWithValue:(jdouble)value__;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsUntil)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsUntil)

#endif // _ComGoogleGsonAnnotationsUntil_H_
