//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/ExclusionStrategy.java
//

#ifndef _ComGoogleGsonExclusionStrategy_H_
#define _ComGoogleGsonExclusionStrategy_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonFieldAttributes;
@class IOSClass;

@protocol ComGoogleGsonExclusionStrategy < NSObject, JavaObject >

- (jboolean)shouldSkipFieldWithComGoogleGsonFieldAttributes:(ComGoogleGsonFieldAttributes *)f;

- (jboolean)shouldSkipClassWithIOSClass:(IOSClass *)clazz;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonExclusionStrategy)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonExclusionStrategy)

#endif // _ComGoogleGsonExclusionStrategy_H_
