//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/FieldNamingStrategy.java
//

#ifndef _ComGoogleGsonFieldNamingStrategy_H_
#define _ComGoogleGsonFieldNamingStrategy_H_

#include "J2ObjC_header.h"

@class JavaLangReflectField;

@protocol ComGoogleGsonFieldNamingStrategy < NSObject, JavaObject >

- (NSString *)translateNameWithJavaLangReflectField:(JavaLangReflectField *)f;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFieldNamingStrategy)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFieldNamingStrategy)

#endif // _ComGoogleGsonFieldNamingStrategy_H_
