//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/FieldNamingPolicy.java
//

#ifndef _ComGoogleGsonFieldNamingPolicy_H_
#define _ComGoogleGsonFieldNamingPolicy_H_

#include "J2ObjC_header.h"
#include "com/google/gson/FieldNamingStrategy.h"
#include "java/lang/Enum.h"

typedef NS_ENUM(NSUInteger, ComGoogleGsonFieldNamingPolicy) {
  ComGoogleGsonFieldNamingPolicy_IDENTITY = 0,
  ComGoogleGsonFieldNamingPolicy_UPPER_CAMEL_CASE = 1,
  ComGoogleGsonFieldNamingPolicy_UPPER_CAMEL_CASE_WITH_SPACES = 2,
  ComGoogleGsonFieldNamingPolicy_LOWER_CASE_WITH_UNDERSCORES = 3,
  ComGoogleGsonFieldNamingPolicy_LOWER_CASE_WITH_DASHES = 4,
};

@interface ComGoogleGsonFieldNamingPolicyEnum : JavaLangEnum < NSCopying, ComGoogleGsonFieldNamingStrategy >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComGoogleGsonFieldNamingPolicyEnum_values();

+ (ComGoogleGsonFieldNamingPolicyEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT ComGoogleGsonFieldNamingPolicyEnum *ComGoogleGsonFieldNamingPolicyEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonFieldNamingPolicyEnum)

FOUNDATION_EXPORT ComGoogleGsonFieldNamingPolicyEnum *ComGoogleGsonFieldNamingPolicyEnum_values_[];

#define ComGoogleGsonFieldNamingPolicyEnum_IDENTITY ComGoogleGsonFieldNamingPolicyEnum_values_[ComGoogleGsonFieldNamingPolicy_IDENTITY]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleGsonFieldNamingPolicyEnum, IDENTITY)

#define ComGoogleGsonFieldNamingPolicyEnum_UPPER_CAMEL_CASE ComGoogleGsonFieldNamingPolicyEnum_values_[ComGoogleGsonFieldNamingPolicy_UPPER_CAMEL_CASE]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleGsonFieldNamingPolicyEnum, UPPER_CAMEL_CASE)

#define ComGoogleGsonFieldNamingPolicyEnum_UPPER_CAMEL_CASE_WITH_SPACES ComGoogleGsonFieldNamingPolicyEnum_values_[ComGoogleGsonFieldNamingPolicy_UPPER_CAMEL_CASE_WITH_SPACES]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleGsonFieldNamingPolicyEnum, UPPER_CAMEL_CASE_WITH_SPACES)

#define ComGoogleGsonFieldNamingPolicyEnum_LOWER_CASE_WITH_UNDERSCORES ComGoogleGsonFieldNamingPolicyEnum_values_[ComGoogleGsonFieldNamingPolicy_LOWER_CASE_WITH_UNDERSCORES]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleGsonFieldNamingPolicyEnum, LOWER_CASE_WITH_UNDERSCORES)

#define ComGoogleGsonFieldNamingPolicyEnum_LOWER_CASE_WITH_DASHES ComGoogleGsonFieldNamingPolicyEnum_values_[ComGoogleGsonFieldNamingPolicy_LOWER_CASE_WITH_DASHES]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleGsonFieldNamingPolicyEnum, LOWER_CASE_WITH_DASHES)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFieldNamingPolicyEnum)

#endif // _ComGoogleGsonFieldNamingPolicy_H_
