//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/FieldNamingStrategy.java
//


#include "J2ObjC_source.h"
#include "com/google/gson/FieldNamingStrategy.h"
#include "java/lang/reflect/Field.h"

@interface ComGoogleGsonFieldNamingStrategy : NSObject
@end

@implementation ComGoogleGsonFieldNamingStrategy

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "translateNameWithJavaLangReflectField:", "translateName", "Ljava.lang.String;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComGoogleGsonFieldNamingStrategy = { 2, "FieldNamingStrategy", "com.google.gson", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonFieldNamingStrategy;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGoogleGsonFieldNamingStrategy)
