//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/InstanceCreator.java
//

#ifndef _ComGoogleGsonInstanceCreator_H_
#define _ComGoogleGsonInstanceCreator_H_

#include "J2ObjC_header.h"

@protocol JavaLangReflectType;

@protocol ComGoogleGsonInstanceCreator < NSObject, JavaObject >

- (id)createInstanceWithJavaLangReflectType:(id<JavaLangReflectType>)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInstanceCreator)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInstanceCreator)

#endif // _ComGoogleGsonInstanceCreator_H_
