//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/LongSerializationPolicy.java
//

#ifndef _ComGoogleGsonLongSerializationPolicy_H_
#define _ComGoogleGsonLongSerializationPolicy_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

@class ComGoogleGsonJsonElement;
@class JavaLangLong;

typedef NS_ENUM(NSUInteger, ComGoogleGsonLongSerializationPolicy) {
  ComGoogleGsonLongSerializationPolicy_DEFAULT = 0,
  ComGoogleGsonLongSerializationPolicy_STRING = 1,
};

@interface ComGoogleGsonLongSerializationPolicyEnum : JavaLangEnum < NSCopying >

#pragma mark Public

- (ComGoogleGsonJsonElement *)serializeWithJavaLangLong:(JavaLangLong *)value;

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComGoogleGsonLongSerializationPolicyEnum_values();

+ (ComGoogleGsonLongSerializationPolicyEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT ComGoogleGsonLongSerializationPolicyEnum *ComGoogleGsonLongSerializationPolicyEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonLongSerializationPolicyEnum)

FOUNDATION_EXPORT ComGoogleGsonLongSerializationPolicyEnum *ComGoogleGsonLongSerializationPolicyEnum_values_[];

#define ComGoogleGsonLongSerializationPolicyEnum_DEFAULT ComGoogleGsonLongSerializationPolicyEnum_values_[ComGoogleGsonLongSerializationPolicy_DEFAULT]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleGsonLongSerializationPolicyEnum, DEFAULT)

#define ComGoogleGsonLongSerializationPolicyEnum_STRING ComGoogleGsonLongSerializationPolicyEnum_values_[ComGoogleGsonLongSerializationPolicy_STRING]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleGsonLongSerializationPolicyEnum, STRING)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonLongSerializationPolicyEnum)

#endif // _ComGoogleGsonLongSerializationPolicy_H_
