//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/TypeAdapterFactory.java
//

#ifndef _ComGoogleGsonTypeAdapterFactory_H_
#define _ComGoogleGsonTypeAdapterFactory_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonReflectTypeToken;
@class ComGoogleGsonTypeAdapter;

@protocol ComGoogleGsonTypeAdapterFactory < NSObject, JavaObject >

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonTypeAdapterFactory)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonTypeAdapterFactory)

#endif // _ComGoogleGsonTypeAdapterFactory_H_
