//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tway/dev/Shelf/shelf-gson/src/main/java/com/toddway/shelf/GsonFileStorage.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/google/gson/Gson.h"
#include "com/google/gson/stream/JsonReader.h"
#include "com/google/gson/stream/JsonWriter.h"
#include "com/toddway/shelf/FileStorage.h"
#include "com/toddway/shelf/GsonFileStorage.h"
#include "java/io/File.h"
#include "java/io/FileNotFoundException.h"
#include "java/io/FileReader.h"
#include "java/io/FileWriter.h"
#include "java/io/IOException.h"
#include "java/lang/Exception.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@implementation ComToddwayShelfGsonFileStorage

- (instancetype)initWithJavaIoFile:(JavaIoFile *)dir {
  ComToddwayShelfGsonFileStorage_initWithJavaIoFile_(self, dir);
  return self;
}

- (id)deserializeWithJavaIoFile:(JavaIoFile *)file
                   withIOSClass:(IOSClass *)type {
  @try {
    ComGoogleGsonStreamJsonReader *reader = new_ComGoogleGsonStreamJsonReader_initWithJavaIoReader_(new_JavaIoFileReader_initWithJavaIoFile_(file));
    return [new_ComGoogleGsonGson_init() fromJsonWithComGoogleGsonStreamJsonReader:reader withJavaLangReflectType:type];
  }
  @catch (JavaIoFileNotFoundException *e) {
    [((JavaIoFileNotFoundException *) nil_chk(e)) printStackTrace];
  }
  return nil;
}

- (void)serializeWithJavaIoFile:(JavaIoFile *)file
                         withId:(id)object {
  @try {
    ComGoogleGsonStreamJsonWriter *writer = new_ComGoogleGsonStreamJsonWriter_initWithJavaIoWriter_(new_JavaIoFileWriter_initWithJavaIoFile_(file));
    [new_ComGoogleGsonGson_init() toJsonWithId:object withJavaLangReflectType:[nil_chk(object) getClass] withComGoogleGsonStreamJsonWriter:writer];
    [writer close];
  }
  @catch (JavaIoIOException *e) {
    [((JavaIoIOException *) nil_chk(e)) printStackTrace];
  }
}

- (id<JavaUtilList>)deserializeListWithJavaIoFile:(JavaIoFile *)file
                                     withIOSClass:(IOSClass *)type {
  @try {
    id<JavaUtilList> list = new_JavaUtilArrayList_init();
    ComGoogleGsonStreamJsonReader *reader = new_ComGoogleGsonStreamJsonReader_initWithJavaIoReader_(new_JavaIoFileReader_initWithJavaIoFile_(file));
    [reader beginArray];
    while ([reader hasNext]) {
      id object = [new_ComGoogleGsonGson_init() fromJsonWithComGoogleGsonStreamJsonReader:reader withJavaLangReflectType:type];
      [list addWithId:object];
    }
    [reader endArray];
    [reader close];
    return list;
  }
  @catch (JavaLangException *e) {
    [((JavaLangException *) nil_chk(e)) printStackTrace];
  }
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoFile:", "GsonFileStorage", NULL, 0x1, NULL, NULL },
    { "deserializeWithJavaIoFile:withIOSClass:", "deserialize", "TT;", 0x4, NULL, "<T:Ljava/lang/Object;>(Ljava/io/File;Ljava/lang/Class<TT;>;)TT;" },
    { "serializeWithJavaIoFile:withId:", "serialize", "V", 0x4, NULL, "<T:Ljava/lang/Object;>(Ljava/io/File;TT;)V" },
    { "deserializeListWithJavaIoFile:withIOSClass:", "deserializeList", "Ljava.util.List;", 0x4, NULL, "<T:Ljava/lang/Object;>(Ljava/io/File;Ljava/lang/Class<TT;>;)Ljava/util/List<TT;>;" },
  };
  static const J2ObjcClassInfo _ComToddwayShelfGsonFileStorage = { 2, "GsonFileStorage", "com.toddway.shelf", NULL, 0x1, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComToddwayShelfGsonFileStorage;
}

@end

void ComToddwayShelfGsonFileStorage_initWithJavaIoFile_(ComToddwayShelfGsonFileStorage *self, JavaIoFile *dir) {
  (void) ComToddwayShelfFileStorage_initWithJavaIoFile_(self, dir);
}

ComToddwayShelfGsonFileStorage *new_ComToddwayShelfGsonFileStorage_initWithJavaIoFile_(JavaIoFile *dir) {
  ComToddwayShelfGsonFileStorage *self = [ComToddwayShelfGsonFileStorage alloc];
  ComToddwayShelfGsonFileStorage_initWithJavaIoFile_(self, dir);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComToddwayShelfGsonFileStorage)
