//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tway/dev/Shelf/shelf-gson/src/main/java/com/toddway/shelf/GsonFileStorage.java
//

#ifndef _ComToddwayShelfGsonFileStorage_H_
#define _ComToddwayShelfGsonFileStorage_H_

#include "J2ObjC_header.h"
#include "com/toddway/shelf/FileStorage.h"

@class IOSClass;
@class JavaIoFile;
@protocol JavaUtilList;

@interface ComToddwayShelfGsonFileStorage : ComToddwayShelfFileStorage

#pragma mark Public

- (instancetype)initWithJavaIoFile:(JavaIoFile *)dir;

#pragma mark Protected

- (id)deserializeWithJavaIoFile:(JavaIoFile *)file
                   withIOSClass:(IOSClass *)type;

- (id<JavaUtilList>)deserializeListWithJavaIoFile:(JavaIoFile *)file
                                     withIOSClass:(IOSClass *)type;

- (void)serializeWithJavaIoFile:(JavaIoFile *)file
                         withId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(ComToddwayShelfGsonFileStorage)

FOUNDATION_EXPORT void ComToddwayShelfGsonFileStorage_initWithJavaIoFile_(ComToddwayShelfGsonFileStorage *self, JavaIoFile *dir);

FOUNDATION_EXPORT ComToddwayShelfGsonFileStorage *new_ComToddwayShelfGsonFileStorage_initWithJavaIoFile_(JavaIoFile *dir) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComToddwayShelfGsonFileStorage)

#endif // _ComToddwayShelfGsonFileStorage_H_
