//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tway/dev/Shelf/shelf/src/main/java/com/toddway/shelf/ShelfItem.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/toddway/shelf/ShelfItem.h"
#include "com/toddway/shelf/Storage.h"
#include "java/util/Date.h"
#include "java/util/List.h"
#include "java/util/concurrent/TimeUnit.h"

@interface ComToddwayShelfShelfItem () {
 @public
  NSString *key_;
  id<ComToddwayShelfStorage> storage_;
  id item_;
}

@end

J2OBJC_FIELD_SETTER(ComToddwayShelfShelfItem, key_, NSString *)
J2OBJC_FIELD_SETTER(ComToddwayShelfShelfItem, storage_, id<ComToddwayShelfStorage>)
J2OBJC_FIELD_SETTER(ComToddwayShelfShelfItem, item_, id)

@implementation ComToddwayShelfShelfItem

- (instancetype)initWithComToddwayShelfStorage:(id<ComToddwayShelfStorage>)storage
                                  withNSString:(NSString *)key {
  ComToddwayShelfShelfItem_initWithComToddwayShelfStorage_withNSString_(self, storage, key);
  return self;
}

- (jboolean)exists {
  return [((id<ComToddwayShelfStorage>) nil_chk(storage_)) containsWithNSString:key_];
}

- (void)putWithId:(id)item {
  self->item_ = item;
  [((id<ComToddwayShelfStorage>) nil_chk(storage_)) putWithNSString:key_ withId:item];
}

- (id)asWithIOSClass:(IOSClass *)type {
  if (item_ != nil) return (id) item_;
  if (![self exists]) return nil;
  return [((id<ComToddwayShelfStorage>) nil_chk(storage_)) getWithNSString:key_ withIOSClass:type];
}

- (id<JavaUtilList>)asListOfWithIOSClass:(IOSClass *)type {
  if (item_ != nil) return (id<JavaUtilList>) check_protocol_cast(item_, @protocol(JavaUtilList));
  if (![self exists]) return nil;
  return [((id<ComToddwayShelfStorage>) nil_chk(storage_)) getListWithNSString:key_ withIOSClass:type];
}

- (jboolean)isOlderThanWithLong:(jlong)value
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit {
  return [self isOlderThanWithLong:[((JavaUtilConcurrentTimeUnitEnum *) nil_chk(unit)) toMillisWithLong:value]];
}

- (jboolean)isOlderThanWithLong:(jlong)millis {
  jboolean isOlderThan = YES;
  if ([self exists]) {
    jlong thenMillis = [((id<ComToddwayShelfStorage>) nil_chk(storage_)) lastModifiedWithNSString:key_];
    jlong nowMillis = [new_JavaUtilDate_init() getTime];
    isOlderThan = (thenMillis < (nowMillis - millis));
  }
  return isOlderThan;
}

- (jboolean)clear {
  item_ = nil;
  return [((id<ComToddwayShelfStorage>) nil_chk(storage_)) delete__WithNSString:key_];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComToddwayShelfStorage:withNSString:", "ShelfItem", NULL, 0x1, NULL, NULL },
    { "exists", NULL, "Z", 0x1, NULL, NULL },
    { "putWithId:", "put", "V", 0x1, NULL, "(TT;)V" },
    { "asWithIOSClass:", "as", "TT;", 0x1, NULL, "<T:Ljava/lang/Object;>(Ljava/lang/Class<TT;>;)TT;" },
    { "asListOfWithIOSClass:", "asListOf", "Ljava.util.List;", 0x1, NULL, "<T:Ljava/lang/Object;>(Ljava/lang/Class<TT;>;)Ljava/util/List<TT;>;" },
    { "isOlderThanWithLong:withJavaUtilConcurrentTimeUnitEnum:", "isOlderThan", "Z", 0x1, NULL, NULL },
    { "isOlderThanWithLong:", "isOlderThan", "Z", 0x1, NULL, NULL },
    { "clear", NULL, "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "key_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL,  },
    { "storage_", NULL, 0x2, "Lcom.toddway.shelf.Storage;", NULL, NULL,  },
    { "item_", NULL, 0x2, "TT;", NULL, "TT;",  },
  };
  static const J2ObjcClassInfo _ComToddwayShelfShelfItem = { 2, "ShelfItem", "com.toddway.shelf", NULL, 0x1, 8, methods, 3, fields, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_ComToddwayShelfShelfItem;
}

@end

void ComToddwayShelfShelfItem_initWithComToddwayShelfStorage_withNSString_(ComToddwayShelfShelfItem *self, id<ComToddwayShelfStorage> storage, NSString *key) {
  (void) NSObject_init(self);
  self->key_ = key;
  self->storage_ = storage;
}

ComToddwayShelfShelfItem *new_ComToddwayShelfShelfItem_initWithComToddwayShelfStorage_withNSString_(id<ComToddwayShelfStorage> storage, NSString *key) {
  ComToddwayShelfShelfItem *self = [ComToddwayShelfShelfItem alloc];
  ComToddwayShelfShelfItem_initWithComToddwayShelfStorage_withNSString_(self, storage, key);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComToddwayShelfShelfItem)
