//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/shelf.jar!com/toddway/shelf/Storage.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/toddway/shelf/Storage.h"
#include "java/io/IOException.h"
#include "java/util/List.h"

@interface ComToddwayShelfStorage : NSObject
@end

@implementation ComToddwayShelfStorage

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getWithNSString:withIOSClass:", "get", "TT;", 0x401, "Ljava.io.IOException;", "<T:Ljava/lang/Object;>(Ljava/lang/String;Ljava/lang/Class<TT;>;)TT;" },
    { "putWithNSString:withId:", "put", "Z", 0x401, "Ljava.io.IOException;", "<T:Ljava/lang/Object;>(Ljava/lang/String;TT;)Z" },
    { "delete__WithNSString:", "delete", "Z", 0x401, "Ljava.io.IOException;", NULL },
    { "containsWithNSString:", "contains", "Z", 0x401, NULL, NULL },
    { "lastModifiedWithNSString:", "lastModified", "J", 0x401, NULL, NULL },
    { "keysWithNSString:", "keys", "Ljava.util.List;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComToddwayShelfStorage = { 2, "Storage", "com.toddway.shelf", NULL, 0x609, 6, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComToddwayShelfStorage;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComToddwayShelfStorage)
