//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tway/dev/Shelf/shelf/src/main/java/com/toddway/shelf/Storage.java
//

#ifndef _ComToddwayShelfStorage_H_
#define _ComToddwayShelfStorage_H_

#include "J2ObjC_header.h"

@class IOSClass;
@protocol JavaUtilList;

@protocol ComToddwayShelfStorage < NSObject, JavaObject >

- (id)getWithNSString:(NSString *)key
         withIOSClass:(IOSClass *)type;

- (id<JavaUtilList>)getListWithNSString:(NSString *)key
                           withIOSClass:(IOSClass *)type;

- (void)putWithNSString:(NSString *)key
                 withId:(id)value;

- (jboolean)delete__WithNSString:(NSString *)key;

- (jboolean)containsWithNSString:(NSString *)key;

- (jlong)lastModifiedWithNSString:(NSString *)key;

- (id<JavaUtilList>)keysWithNSString:(NSString *)startsWith;

@end

J2OBJC_EMPTY_STATIC_INIT(ComToddwayShelfStorage)

J2OBJC_TYPE_LITERAL_HEADER(ComToddwayShelfStorage)

#endif // _ComToddwayShelfStorage_H_
