//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/reflect/TypeToken.java
//

#ifndef _ComGoogleGsonReflectTypeToken_H_
#define _ComGoogleGsonReflectTypeToken_H_

#include "J2ObjC_header.h"

@class IOSClass;
@protocol JavaLangReflectType;

@interface ComGoogleGsonReflectTypeToken : NSObject {
 @public
  IOSClass *rawType_;
  id<JavaLangReflectType> type_;
  jint hashCode__;
}

#pragma mark Public

- (jboolean)isEqual:(id)o;

+ (ComGoogleGsonReflectTypeToken *)getWithIOSClass:(IOSClass *)type;

+ (ComGoogleGsonReflectTypeToken *)getWithJavaLangReflectType:(id<JavaLangReflectType>)type;

- (IOSClass *)getRawType;

- (id<JavaLangReflectType>)getType;

- (NSUInteger)hash;

- (jboolean)isAssignableFromWithIOSClass:(IOSClass *)cls;

- (jboolean)isAssignableFromWithJavaLangReflectType:(id<JavaLangReflectType>)from;

- (jboolean)isAssignableFromWithComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)token;

- (NSString *)description;

#pragma mark Protected

- (instancetype)init;

#pragma mark Package-Private

- (instancetype)initWithJavaLangReflectType:(id<JavaLangReflectType>)type;

+ (id<JavaLangReflectType>)getSuperclassTypeParameterWithIOSClass:(IOSClass *)subclass;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonReflectTypeToken)

J2OBJC_FIELD_SETTER(ComGoogleGsonReflectTypeToken, rawType_, IOSClass *)
J2OBJC_FIELD_SETTER(ComGoogleGsonReflectTypeToken, type_, id<JavaLangReflectType>)

FOUNDATION_EXPORT void ComGoogleGsonReflectTypeToken_init(ComGoogleGsonReflectTypeToken *self);

FOUNDATION_EXPORT ComGoogleGsonReflectTypeToken *new_ComGoogleGsonReflectTypeToken_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonReflectTypeToken_initWithJavaLangReflectType_(ComGoogleGsonReflectTypeToken *self, id<JavaLangReflectType> type);

FOUNDATION_EXPORT ComGoogleGsonReflectTypeToken *new_ComGoogleGsonReflectTypeToken_initWithJavaLangReflectType_(id<JavaLangReflectType> type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT id<JavaLangReflectType> ComGoogleGsonReflectTypeToken_getSuperclassTypeParameterWithIOSClass_(IOSClass *subclass);

FOUNDATION_EXPORT ComGoogleGsonReflectTypeToken *ComGoogleGsonReflectTypeToken_getWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT ComGoogleGsonReflectTypeToken *ComGoogleGsonReflectTypeToken_getWithIOSClass_(IOSClass *type);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonReflectTypeToken)

#endif // _ComGoogleGsonReflectTypeToken_H_
