//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tway/dev/FeedRead/core/src/main/java/com/example/domain/ArticleRepository.java
//


#include "ArticleRepository.h"
#include "J2ObjC_source.h"
#include "java/util/List.h"

@interface ComExampleDomainArticleRepository : NSObject
@end

@implementation ComExampleDomainArticleRepository

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getArticlesWithNSString:", "getArticles", "Ljava.util.List;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComExampleDomainArticleRepository = { 2, "ArticleRepository", "com.example.domain", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleDomainArticleRepository;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComExampleDomainArticleRepository)
