//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/shelf.jar!com/toddway/shelf/FileStorage.java
//

#ifndef _ComToddwayShelfFileStorage_H_
#define _ComToddwayShelfFileStorage_H_

#include "J2ObjC_header.h"
#include "Storage.h"

@class IOSClass;
@class JavaIoFile;
@protocol JavaUtilList;

@interface ComToddwayShelfFileStorage : NSObject < ComToddwayShelfStorage > {
 @public
  JavaIoFile *dir_;
}

#pragma mark Public

- (instancetype)initWithJavaIoFile:(JavaIoFile *)dir;

- (jboolean)containsWithNSString:(NSString *)key;

- (jboolean)delete__WithNSString:(NSString *)key;

- (id)getWithNSString:(NSString *)key
         withIOSClass:(IOSClass *)type;

- (id<JavaUtilList>)keysWithNSString:(NSString *)prefix;

- (jlong)lastModifiedWithNSString:(NSString *)key;

- (jboolean)putWithNSString:(NSString *)key
                     withId:(id)value;

+ (NSString *)readFileStringWithJavaIoFile:(JavaIoFile *)file;

+ (id)readObjectFileWithJavaIoFile:(JavaIoFile *)file
                      withIOSClass:(IOSClass *)clazz;

+ (void)writeFileStringWithJavaIoFile:(JavaIoFile *)file
                         withNSString:(NSString *)fileString;

+ (void)writeObjectFileWithJavaIoFile:(JavaIoFile *)file
                               withId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(ComToddwayShelfFileStorage)

J2OBJC_FIELD_SETTER(ComToddwayShelfFileStorage, dir_, JavaIoFile *)

FOUNDATION_EXPORT NSString *ComToddwayShelfFileStorage_EXT_;
J2OBJC_STATIC_FIELD_GETTER(ComToddwayShelfFileStorage, EXT_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(ComToddwayShelfFileStorage, EXT_, NSString *)

FOUNDATION_EXPORT void ComToddwayShelfFileStorage_initWithJavaIoFile_(ComToddwayShelfFileStorage *self, JavaIoFile *dir);

FOUNDATION_EXPORT ComToddwayShelfFileStorage *new_ComToddwayShelfFileStorage_initWithJavaIoFile_(JavaIoFile *dir) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT id ComToddwayShelfFileStorage_readObjectFileWithJavaIoFile_withIOSClass_(JavaIoFile *file, IOSClass *clazz);

FOUNDATION_EXPORT void ComToddwayShelfFileStorage_writeObjectFileWithJavaIoFile_withId_(JavaIoFile *file, id object);

FOUNDATION_EXPORT NSString *ComToddwayShelfFileStorage_readFileStringWithJavaIoFile_(JavaIoFile *file);

FOUNDATION_EXPORT void ComToddwayShelfFileStorage_writeFileStringWithJavaIoFile_withNSString_(JavaIoFile *file, NSString *fileString);

J2OBJC_TYPE_LITERAL_HEADER(ComToddwayShelfFileStorage)

#endif // _ComToddwayShelfFileStorage_H_
