//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/internal/bind/JsonAdapterAnnotationTypeAdapterFactory.java
//

#ifndef _ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_H_
#define _ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_H_

#include "J2ObjC_header.h"
#include "com/google/gson/TypeAdapterFactory.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonInternalConstructorConstructor;
@class ComGoogleGsonReflectTypeToken;
@class ComGoogleGsonTypeAdapter;
@protocol ComGoogleGsonAnnotationsJsonAdapter;

@interface ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory : NSObject < ComGoogleGsonTypeAdapterFactory >

#pragma mark Public

- (instancetype)initWithComGoogleGsonInternalConstructorConstructor:(ComGoogleGsonInternalConstructorConstructor *)constructorConstructor;

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)targetType;

#pragma mark Package-Private

+ (ComGoogleGsonTypeAdapter *)getTypeAdapterWithComGoogleGsonInternalConstructorConstructor:(ComGoogleGsonInternalConstructorConstructor *)constructorConstructor
                                                                      withComGoogleGsonGson:(ComGoogleGsonGson *)gson
                                                          withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)fieldType
                                                    withComGoogleGsonAnnotationsJsonAdapter:(id<ComGoogleGsonAnnotationsJsonAdapter>)annotation;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory)

FOUNDATION_EXPORT void ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory *self, ComGoogleGsonInternalConstructorConstructor *constructorConstructor);

FOUNDATION_EXPORT ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory *new_ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(ComGoogleGsonInternalConstructorConstructor *constructorConstructor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_getTypeAdapterWithComGoogleGsonInternalConstructorConstructor_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_withComGoogleGsonAnnotationsJsonAdapter_(ComGoogleGsonInternalConstructorConstructor *constructorConstructor, ComGoogleGsonGson *gson, ComGoogleGsonReflectTypeToken *fieldType, id<ComGoogleGsonAnnotationsJsonAdapter> annotation);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory)

#endif // _ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_H_
