//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/internal/bind/JsonTreeReader.java
//

#ifndef _ComGoogleGsonInternalBindJsonTreeReader_H_
#define _ComGoogleGsonInternalBindJsonTreeReader_H_

#include "J2ObjC_header.h"
#include "com/google/gson/stream/JsonReader.h"

@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonTokenEnum;

@interface ComGoogleGsonInternalBindJsonTreeReader : ComGoogleGsonStreamJsonReader

#pragma mark Public

- (instancetype)initWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)element;

- (void)beginArray;

- (void)beginObject;

- (void)close;

- (void)endArray;

- (void)endObject;

- (jboolean)hasNext;

- (jboolean)nextBoolean;

- (jdouble)nextDouble;

- (jint)nextInt;

- (jlong)nextLong;

- (NSString *)nextName;

- (void)nextNull;

- (NSString *)nextString;

- (ComGoogleGsonStreamJsonTokenEnum *)peek;

- (void)promoteNameToValue;

- (void)skipValue;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonInternalBindJsonTreeReader)

FOUNDATION_EXPORT void ComGoogleGsonInternalBindJsonTreeReader_initWithComGoogleGsonJsonElement_(ComGoogleGsonInternalBindJsonTreeReader *self, ComGoogleGsonJsonElement *element);

FOUNDATION_EXPORT ComGoogleGsonInternalBindJsonTreeReader *new_ComGoogleGsonInternalBindJsonTreeReader_initWithComGoogleGsonJsonElement_(ComGoogleGsonJsonElement *element) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindJsonTreeReader)

#endif // _ComGoogleGsonInternalBindJsonTreeReader_H_
