//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/internal/bind/ObjectTypeAdapter.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/google/gson/Gson.h"
#include "com/google/gson/TypeAdapter.h"
#include "com/google/gson/TypeAdapterFactory.h"
#include "com/google/gson/internal/LinkedTreeMap.h"
#include "com/google/gson/internal/bind/ObjectTypeAdapter.h"
#include "com/google/gson/reflect/TypeToken.h"
#include "com/google/gson/stream/JsonReader.h"
#include "com/google/gson/stream/JsonToken.h"
#include "com/google/gson/stream/JsonWriter.h"
#include "java/io/IOException.h"
#include "java/lang/Boolean.h"
#include "java/lang/Double.h"
#include "java/lang/IllegalStateException.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"
#include "java/util/Map.h"

@interface ComGoogleGsonInternalBindObjectTypeAdapter () {
 @public
  ComGoogleGsonGson *gson_;
}

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindObjectTypeAdapter, gson_, ComGoogleGsonGson *)

__attribute__((unused)) static void ComGoogleGsonInternalBindObjectTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonInternalBindObjectTypeAdapter *self, ComGoogleGsonGson *gson);

__attribute__((unused)) static ComGoogleGsonInternalBindObjectTypeAdapter *new_ComGoogleGsonInternalBindObjectTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

@interface ComGoogleGsonInternalBindObjectTypeAdapter_$1 : NSObject < ComGoogleGsonTypeAdapterFactory >

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalBindObjectTypeAdapter_$1)

__attribute__((unused)) static void ComGoogleGsonInternalBindObjectTypeAdapter_$1_init(ComGoogleGsonInternalBindObjectTypeAdapter_$1 *self);

__attribute__((unused)) static ComGoogleGsonInternalBindObjectTypeAdapter_$1 *new_ComGoogleGsonInternalBindObjectTypeAdapter_$1_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindObjectTypeAdapter_$1)

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonInternalBindObjectTypeAdapter)

id<ComGoogleGsonTypeAdapterFactory> ComGoogleGsonInternalBindObjectTypeAdapter_FACTORY_;

@implementation ComGoogleGsonInternalBindObjectTypeAdapter

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson {
  ComGoogleGsonInternalBindObjectTypeAdapter_initWithComGoogleGsonGson_(self, gson);
  return self;
}

- (id)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg {
  ComGoogleGsonStreamJsonTokenEnum *token = [((ComGoogleGsonStreamJsonReader *) nil_chk(inArg)) peek];
  {
    id<JavaUtilList> list;
    id<JavaUtilMap> map;
    switch ([token ordinal]) {
      case ComGoogleGsonStreamJsonToken_BEGIN_ARRAY:
      list = new_JavaUtilArrayList_init();
      [inArg beginArray];
      while ([inArg hasNext]) {
        [list addWithId:[self readWithComGoogleGsonStreamJsonReader:inArg]];
      }
      [inArg endArray];
      return list;
      case ComGoogleGsonStreamJsonToken_BEGIN_OBJECT:
      map = new_ComGoogleGsonInternalLinkedTreeMap_init();
      [inArg beginObject];
      while ([inArg hasNext]) {
        (void) [map putWithId:[inArg nextName] withId:[self readWithComGoogleGsonStreamJsonReader:inArg]];
      }
      [inArg endObject];
      return map;
      case ComGoogleGsonStreamJsonToken_STRING:
      return [inArg nextString];
      case ComGoogleGsonStreamJsonToken_NUMBER:
      return JavaLangDouble_valueOfWithDouble_([inArg nextDouble]);
      case ComGoogleGsonStreamJsonToken_BOOLEAN:
      return JavaLangBoolean_valueOfWithBoolean_([inArg nextBoolean]);
      case ComGoogleGsonStreamJsonToken_NULL:
      [inArg nextNull];
      return nil;
      default:
      @throw new_JavaLangIllegalStateException_init();
    }
  }
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(id)value {
  if (value == nil) {
    (void) [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  ComGoogleGsonTypeAdapter *typeAdapter = (ComGoogleGsonTypeAdapter *) check_class_cast([((ComGoogleGsonGson *) nil_chk(gson_)) getAdapterWithIOSClass:[nil_chk(value) getClass]], [ComGoogleGsonTypeAdapter class]);
  if ([typeAdapter isKindOfClass:[ComGoogleGsonInternalBindObjectTypeAdapter class]]) {
    (void) [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) beginObject];
    (void) [outArg endObject];
    return;
  }
  [((ComGoogleGsonTypeAdapter *) nil_chk(typeAdapter)) writeWithComGoogleGsonStreamJsonWriter:outArg withId:value];
}

+ (void)initialize {
  if (self == [ComGoogleGsonInternalBindObjectTypeAdapter class]) {
    ComGoogleGsonInternalBindObjectTypeAdapter_FACTORY_ = new_ComGoogleGsonInternalBindObjectTypeAdapter_$1_init();
    J2OBJC_SET_INITIALIZED(ComGoogleGsonInternalBindObjectTypeAdapter)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComGoogleGsonGson:", "ObjectTypeAdapter", NULL, 0x2, NULL, NULL },
    { "readWithComGoogleGsonStreamJsonReader:", "read", "Ljava.lang.Object;", 0x1, "Ljava.io.IOException;", NULL },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "FACTORY_", NULL, 0x19, "Lcom.google.gson.TypeAdapterFactory;", &ComGoogleGsonInternalBindObjectTypeAdapter_FACTORY_, NULL,  },
    { "gson_", NULL, 0x12, "Lcom.google.gson.Gson;", NULL, NULL,  },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.Object;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalBindObjectTypeAdapter = { 2, "ObjectTypeAdapter", "com.google.gson.internal.bind", NULL, 0x11, 3, methods, 2, fields, 1, superclass_type_args, 0, NULL, NULL, "Lcom/google/gson/TypeAdapter<Ljava/lang/Object;>;" };
  return &_ComGoogleGsonInternalBindObjectTypeAdapter;
}

@end

void ComGoogleGsonInternalBindObjectTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonInternalBindObjectTypeAdapter *self, ComGoogleGsonGson *gson) {
  (void) ComGoogleGsonTypeAdapter_init(self);
  self->gson_ = gson;
}

ComGoogleGsonInternalBindObjectTypeAdapter *new_ComGoogleGsonInternalBindObjectTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) {
  ComGoogleGsonInternalBindObjectTypeAdapter *self = [ComGoogleGsonInternalBindObjectTypeAdapter alloc];
  ComGoogleGsonInternalBindObjectTypeAdapter_initWithComGoogleGsonGson_(self, gson);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalBindObjectTypeAdapter)

@implementation ComGoogleGsonInternalBindObjectTypeAdapter_$1

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type {
  if ([((ComGoogleGsonReflectTypeToken *) nil_chk(type)) getRawType] == NSObject_class_()) {
    return (ComGoogleGsonTypeAdapter *) check_class_cast(new_ComGoogleGsonInternalBindObjectTypeAdapter_initWithComGoogleGsonGson_(gson), [ComGoogleGsonTypeAdapter class]);
  }
  return nil;
}

- (instancetype)init {
  ComGoogleGsonInternalBindObjectTypeAdapter_$1_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createWithComGoogleGsonGson:withComGoogleGsonReflectTypeToken:", "create", "Lcom.google.gson.TypeAdapter;", 0x1, NULL, "<T:Ljava/lang/Object;>(Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalBindObjectTypeAdapter_$1 = { 2, "", "com.google.gson.internal.bind", "ObjectTypeAdapter", 0x8008, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonInternalBindObjectTypeAdapter_$1;
}

@end

void ComGoogleGsonInternalBindObjectTypeAdapter_$1_init(ComGoogleGsonInternalBindObjectTypeAdapter_$1 *self) {
  (void) NSObject_init(self);
}

ComGoogleGsonInternalBindObjectTypeAdapter_$1 *new_ComGoogleGsonInternalBindObjectTypeAdapter_$1_init() {
  ComGoogleGsonInternalBindObjectTypeAdapter_$1 *self = [ComGoogleGsonInternalBindObjectTypeAdapter_$1 alloc];
  ComGoogleGsonInternalBindObjectTypeAdapter_$1_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalBindObjectTypeAdapter_$1)
