//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tway/dev/FeedRead/core/src/test/java/com/example/domain/ArticleListInteractorTests.java
//

#ifndef _ComExampleDomainArticleListInteractorTests_H_
#define _ComExampleDomainArticleListInteractorTests_H_

#include "J2ObjC_header.h"

@class ComExampleDomainArticleListInteractor;
@class ComToddwayShelfShelf;
@protocol ComExampleDomainArticleRepository;

@interface ComExampleDomainArticleListInteractorTests : NSObject {
 @public
  ComExampleDomainArticleListInteractor *articleListInteractor_;
  id<ComExampleDomainArticleRepository> articleRepository_;
  ComToddwayShelfShelf *diskCache_;
  NSString *url_;
}

#pragma mark Public

- (instancetype)init;

- (void)beforeEach;

- (void)testGetArticleTitle;

- (void)testGetArticleTitleIgnoringCache;

- (void)testGetArticleTitleUsingCache;

- (void)testPrintArticles;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleDomainArticleListInteractorTests)

J2OBJC_FIELD_SETTER(ComExampleDomainArticleListInteractorTests, articleListInteractor_, ComExampleDomainArticleListInteractor *)
J2OBJC_FIELD_SETTER(ComExampleDomainArticleListInteractorTests, articleRepository_, id<ComExampleDomainArticleRepository>)
J2OBJC_FIELD_SETTER(ComExampleDomainArticleListInteractorTests, diskCache_, ComToddwayShelfShelf *)
J2OBJC_FIELD_SETTER(ComExampleDomainArticleListInteractorTests, url_, NSString *)

FOUNDATION_EXPORT void ComExampleDomainArticleListInteractorTests_init(ComExampleDomainArticleListInteractorTests *self);

FOUNDATION_EXPORT ComExampleDomainArticleListInteractorTests *new_ComExampleDomainArticleListInteractorTests_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComExampleDomainArticleListInteractorTests)

#endif // _ComExampleDomainArticleListInteractorTests_H_
