//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tway/dev/FeedRead/core/src/test/java/com/example/domain/HttpArticleListTests.java
//

#ifndef _ComExampleDomainHttpArticleListTests_H_
#define _ComExampleDomainHttpArticleListTests_H_

#include "J2ObjC_header.h"

@class ComExampleDomainArticleListInteractor;
@protocol ComExampleDomainArticleRepository;

@interface ComExampleDomainHttpArticleListTests : NSObject {
 @public
  ComExampleDomainArticleListInteractor *articleListInteractor_;
  id<ComExampleDomainArticleRepository> articleRepository_;
}

#pragma mark Public

- (instancetype)init;

- (void)beforeEach;

- (void)testSomething;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleDomainHttpArticleListTests)

J2OBJC_FIELD_SETTER(ComExampleDomainHttpArticleListTests, articleListInteractor_, ComExampleDomainArticleListInteractor *)
J2OBJC_FIELD_SETTER(ComExampleDomainHttpArticleListTests, articleRepository_, id<ComExampleDomainArticleRepository>)

FOUNDATION_EXPORT NSString *ComExampleDomainHttpArticleListTests_URL_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleDomainHttpArticleListTests, URL_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(ComExampleDomainHttpArticleListTests, URL_, NSString *)

FOUNDATION_EXPORT void ComExampleDomainHttpArticleListTests_init(ComExampleDomainHttpArticleListTests *self);

FOUNDATION_EXPORT ComExampleDomainHttpArticleListTests *new_ComExampleDomainHttpArticleListTests_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComExampleDomainHttpArticleListTests)

#endif // _ComExampleDomainHttpArticleListTests_H_
