//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/stream/JsonReader.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/google/gson/internal/JsonReaderInternalAccess.h"
#include "com/google/gson/internal/bind/JsonTreeReader.h"
#include "com/google/gson/stream/JsonReader.h"
#include "com/google/gson/stream/JsonScope.h"
#include "com/google/gson/stream/JsonToken.h"
#include "com/google/gson/stream/MalformedJsonException.h"
#include "java/io/EOFException.h"
#include "java/io/IOException.h"
#include "java/io/Reader.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Double.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/NullPointerException.h"
#include "java/lang/NumberFormatException.h"
#include "java/lang/StringBuilder.h"
#include "java/lang/System.h"

#define ComGoogleGsonStreamJsonReader_MIN_INCOMPLETE_INTEGER -922337203685477580LL
#define ComGoogleGsonStreamJsonReader_PEEKED_NONE 0
#define ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_OBJECT 1
#define ComGoogleGsonStreamJsonReader_PEEKED_END_OBJECT 2
#define ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_ARRAY 3
#define ComGoogleGsonStreamJsonReader_PEEKED_END_ARRAY 4
#define ComGoogleGsonStreamJsonReader_PEEKED_TRUE 5
#define ComGoogleGsonStreamJsonReader_PEEKED_FALSE 6
#define ComGoogleGsonStreamJsonReader_PEEKED_NULL 7
#define ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED 8
#define ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED 9
#define ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED 10
#define ComGoogleGsonStreamJsonReader_PEEKED_BUFFERED 11
#define ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED_NAME 12
#define ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED_NAME 13
#define ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED_NAME 14
#define ComGoogleGsonStreamJsonReader_PEEKED_LONG 15
#define ComGoogleGsonStreamJsonReader_PEEKED_NUMBER 16
#define ComGoogleGsonStreamJsonReader_PEEKED_EOF 17
#define ComGoogleGsonStreamJsonReader_NUMBER_CHAR_NONE 0
#define ComGoogleGsonStreamJsonReader_NUMBER_CHAR_SIGN 1
#define ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DIGIT 2
#define ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DECIMAL 3
#define ComGoogleGsonStreamJsonReader_NUMBER_CHAR_FRACTION_DIGIT 4
#define ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_E 5
#define ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_SIGN 6
#define ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_DIGIT 7

@interface ComGoogleGsonStreamJsonReader () {
 @public
  JavaIoReader *in_;
  jboolean lenient_;
  IOSCharArray *buffer_;
  jint pos_;
  jint limit_;
  jint lineNumber_;
  jint lineStart_;
  jint peeked_;
  jlong peekedLong_;
  jint peekedNumberLength_;
  NSString *peekedString_;
  IOSIntArray *stack_;
  jint stackSize_;
  IOSObjectArray *pathNames_;
  IOSIntArray *pathIndices_;
}

- (jint)doPeek;

- (jint)peekKeyword;

- (jint)peekNumber;

- (jboolean)isLiteralWithChar:(jchar)c;

- (NSString *)nextQuotedValueWithChar:(jchar)quote;

- (NSString *)nextUnquotedValue;

- (void)skipQuotedValueWithChar:(jchar)quote;

- (void)skipUnquotedValue;

- (void)pushWithInt:(jint)newTop;

- (jboolean)fillBufferWithInt:(jint)minimum;

- (jint)getLineNumber;

- (jint)getColumnNumber;

- (jint)nextNonWhitespaceWithBoolean:(jboolean)throwOnEof;

- (void)checkLenient;

- (void)skipToEndOfLine;

- (jboolean)skipToWithNSString:(NSString *)toFind;

- (jchar)readEscapeCharacter;

- (JavaIoIOException *)syntaxErrorWithNSString:(NSString *)message;

- (void)consumeNonExecutePrefix;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonStreamJsonReader, in_, JavaIoReader *)
J2OBJC_FIELD_SETTER(ComGoogleGsonStreamJsonReader, buffer_, IOSCharArray *)
J2OBJC_FIELD_SETTER(ComGoogleGsonStreamJsonReader, peekedString_, NSString *)
J2OBJC_FIELD_SETTER(ComGoogleGsonStreamJsonReader, stack_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ComGoogleGsonStreamJsonReader, pathNames_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(ComGoogleGsonStreamJsonReader, pathIndices_, IOSIntArray *)

static IOSCharArray *ComGoogleGsonStreamJsonReader_NON_EXECUTE_PREFIX_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NON_EXECUTE_PREFIX_, IOSCharArray *)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, MIN_INCOMPLETE_INTEGER, jlong)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_NONE, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_BEGIN_OBJECT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_END_OBJECT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_BEGIN_ARRAY, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_END_ARRAY, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_TRUE, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_FALSE, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_NULL, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_SINGLE_QUOTED, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_DOUBLE_QUOTED, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_UNQUOTED, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_BUFFERED, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_SINGLE_QUOTED_NAME, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_DOUBLE_QUOTED_NAME, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_UNQUOTED_NAME, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_LONG, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_NUMBER, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, PEEKED_EOF, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NUMBER_CHAR_NONE, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NUMBER_CHAR_SIGN, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NUMBER_CHAR_DIGIT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NUMBER_CHAR_DECIMAL, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NUMBER_CHAR_FRACTION_DIGIT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NUMBER_CHAR_EXP_E, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NUMBER_CHAR_EXP_SIGN, jint)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonStreamJsonReader, NUMBER_CHAR_EXP_DIGIT, jint)

__attribute__((unused)) static jint ComGoogleGsonStreamJsonReader_doPeek(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static jint ComGoogleGsonStreamJsonReader_peekKeyword(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static jint ComGoogleGsonStreamJsonReader_peekNumber(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static jboolean ComGoogleGsonStreamJsonReader_isLiteralWithChar_(ComGoogleGsonStreamJsonReader *self, jchar c);

__attribute__((unused)) static NSString *ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(ComGoogleGsonStreamJsonReader *self, jchar quote);

__attribute__((unused)) static NSString *ComGoogleGsonStreamJsonReader_nextUnquotedValue(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static void ComGoogleGsonStreamJsonReader_skipQuotedValueWithChar_(ComGoogleGsonStreamJsonReader *self, jchar quote);

__attribute__((unused)) static void ComGoogleGsonStreamJsonReader_skipUnquotedValue(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static void ComGoogleGsonStreamJsonReader_pushWithInt_(ComGoogleGsonStreamJsonReader *self, jint newTop);

__attribute__((unused)) static jboolean ComGoogleGsonStreamJsonReader_fillBufferWithInt_(ComGoogleGsonStreamJsonReader *self, jint minimum);

__attribute__((unused)) static jint ComGoogleGsonStreamJsonReader_getLineNumber(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static jint ComGoogleGsonStreamJsonReader_getColumnNumber(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static jint ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(ComGoogleGsonStreamJsonReader *self, jboolean throwOnEof);

__attribute__((unused)) static void ComGoogleGsonStreamJsonReader_checkLenient(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static void ComGoogleGsonStreamJsonReader_skipToEndOfLine(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static jboolean ComGoogleGsonStreamJsonReader_skipToWithNSString_(ComGoogleGsonStreamJsonReader *self, NSString *toFind);

__attribute__((unused)) static jchar ComGoogleGsonStreamJsonReader_readEscapeCharacter(ComGoogleGsonStreamJsonReader *self);

__attribute__((unused)) static JavaIoIOException *ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(ComGoogleGsonStreamJsonReader *self, NSString *message);

__attribute__((unused)) static void ComGoogleGsonStreamJsonReader_consumeNonExecutePrefix(ComGoogleGsonStreamJsonReader *self);

@interface ComGoogleGsonStreamJsonReader_$1 : ComGoogleGsonInternalJsonReaderInternalAccess

- (void)promoteNameToValueWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonStreamJsonReader_$1)

__attribute__((unused)) static void ComGoogleGsonStreamJsonReader_$1_init(ComGoogleGsonStreamJsonReader_$1 *self);

__attribute__((unused)) static ComGoogleGsonStreamJsonReader_$1 *new_ComGoogleGsonStreamJsonReader_$1_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonStreamJsonReader_$1)

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonStreamJsonReader)

@implementation ComGoogleGsonStreamJsonReader

- (instancetype)initWithJavaIoReader:(JavaIoReader *)inArg {
  ComGoogleGsonStreamJsonReader_initWithJavaIoReader_(self, inArg);
  return self;
}

- (void)setLenientWithBoolean:(jboolean)lenient {
  self->lenient_ = lenient;
}

- (jboolean)isLenient {
  return lenient_;
}

- (void)beginArray {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_ARRAY) {
    ComGoogleGsonStreamJsonReader_pushWithInt_(self, ComGoogleGsonStreamJsonScope_EMPTY_ARRAY);
    *IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1) = 0;
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected BEGIN_ARRAY but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
}

- (void)endArray {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_END_ARRAY) {
    stackSize_--;
    (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected END_ARRAY but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
}

- (void)beginObject {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_OBJECT) {
    ComGoogleGsonStreamJsonReader_pushWithInt_(self, ComGoogleGsonStreamJsonScope_EMPTY_OBJECT);
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected BEGIN_OBJECT but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
}

- (void)endObject {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_END_OBJECT) {
    stackSize_--;
    (void) IOSObjectArray_Set(nil_chk(pathNames_), stackSize_, nil);
    (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected END_OBJECT but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
}

- (jboolean)hasNext {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  return p != ComGoogleGsonStreamJsonReader_PEEKED_END_OBJECT && p != ComGoogleGsonStreamJsonReader_PEEKED_END_ARRAY;
}

- (ComGoogleGsonStreamJsonTokenEnum *)peek {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  switch (p) {
    case ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_OBJECT:
    return ComGoogleGsonStreamJsonTokenEnum_get_BEGIN_OBJECT();
    case ComGoogleGsonStreamJsonReader_PEEKED_END_OBJECT:
    return ComGoogleGsonStreamJsonTokenEnum_get_END_OBJECT();
    case ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_ARRAY:
    return ComGoogleGsonStreamJsonTokenEnum_get_BEGIN_ARRAY();
    case ComGoogleGsonStreamJsonReader_PEEKED_END_ARRAY:
    return ComGoogleGsonStreamJsonTokenEnum_get_END_ARRAY();
    case ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED_NAME:
    case ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED_NAME:
    case ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED_NAME:
    return ComGoogleGsonStreamJsonTokenEnum_get_NAME();
    case ComGoogleGsonStreamJsonReader_PEEKED_TRUE:
    case ComGoogleGsonStreamJsonReader_PEEKED_FALSE:
    return ComGoogleGsonStreamJsonTokenEnum_get_BOOLEAN();
    case ComGoogleGsonStreamJsonReader_PEEKED_NULL:
    return ComGoogleGsonStreamJsonTokenEnum_get_NULL();
    case ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED:
    case ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED:
    case ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED:
    case ComGoogleGsonStreamJsonReader_PEEKED_BUFFERED:
    return ComGoogleGsonStreamJsonTokenEnum_get_STRING();
    case ComGoogleGsonStreamJsonReader_PEEKED_LONG:
    case ComGoogleGsonStreamJsonReader_PEEKED_NUMBER:
    return ComGoogleGsonStreamJsonTokenEnum_get_NUMBER();
    case ComGoogleGsonStreamJsonReader_PEEKED_EOF:
    return ComGoogleGsonStreamJsonTokenEnum_get_END_DOCUMENT();
    default:
    @throw new_JavaLangAssertionError_init();
  }
}

- (jint)doPeek {
  return ComGoogleGsonStreamJsonReader_doPeek(self);
}

- (jint)peekKeyword {
  return ComGoogleGsonStreamJsonReader_peekKeyword(self);
}

- (jint)peekNumber {
  return ComGoogleGsonStreamJsonReader_peekNumber(self);
}

- (jboolean)isLiteralWithChar:(jchar)c {
  return ComGoogleGsonStreamJsonReader_isLiteralWithChar_(self, c);
}

- (NSString *)nextName {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  NSString *result;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED_NAME) {
    result = ComGoogleGsonStreamJsonReader_nextUnquotedValue(self);
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED_NAME) {
    result = ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(self, '\'');
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED_NAME) {
    result = ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(self, '"');
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected a name but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  (void) IOSObjectArray_Set(nil_chk(pathNames_), stackSize_ - 1, result);
  return result;
}

- (NSString *)nextString {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  NSString *result;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED) {
    result = ComGoogleGsonStreamJsonReader_nextUnquotedValue(self);
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED) {
    result = ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(self, '\'');
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED) {
    result = ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(self, '"');
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_BUFFERED) {
    result = peekedString_;
    peekedString_ = nil;
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_LONG) {
    result = JavaLangLong_toStringWithLong_(peekedLong_);
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_NUMBER) {
    result = [NSString stringWithCharacters:buffer_ offset:pos_ length:peekedNumberLength_];
    pos_ += peekedNumberLength_;
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected a string but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
  return result;
}

- (jboolean)nextBoolean {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_TRUE) {
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
    (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
    return YES;
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_FALSE) {
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
    (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
    return NO;
  }
  @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected a boolean but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
}

- (void)nextNull {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NULL) {
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
    (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected null but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
}

- (jdouble)nextDouble {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_LONG) {
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
    (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
    return (jdouble) peekedLong_;
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NUMBER) {
    peekedString_ = [NSString stringWithCharacters:buffer_ offset:pos_ length:peekedNumberLength_];
    pos_ += peekedNumberLength_;
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED || p == ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED) {
    peekedString_ = ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(self, p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED ? '\'' : '"');
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED) {
    peekedString_ = ComGoogleGsonStreamJsonReader_nextUnquotedValue(self);
  }
  else if (p != ComGoogleGsonStreamJsonReader_PEEKED_BUFFERED) {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected a double but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_BUFFERED;
  jdouble result = JavaLangDouble_parseDoubleWithNSString_(peekedString_);
  if (!lenient_ && (JavaLangDouble_isNaNWithDouble_(result) || JavaLangDouble_isInfiniteWithDouble_(result))) {
    @throw new_ComGoogleGsonStreamMalformedJsonException_initWithNSString_(JreStrcat("$D$I$I$$", @"JSON forbids NaN and infinities: ", result, @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
  peekedString_ = nil;
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
  return result;
}

- (jlong)nextLong {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_LONG) {
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
    (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
    return peekedLong_;
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NUMBER) {
    peekedString_ = [NSString stringWithCharacters:buffer_ offset:pos_ length:peekedNumberLength_];
    pos_ += peekedNumberLength_;
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED || p == ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED) {
    peekedString_ = ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(self, p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED ? '\'' : '"');
    @try {
      jlong result = JavaLangLong_parseLongWithNSString_(peekedString_);
      peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
      (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
      return result;
    }
    @catch (JavaLangNumberFormatException *ignored) {
    }
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected a long but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_BUFFERED;
  jdouble asDouble = JavaLangDouble_parseDoubleWithNSString_(peekedString_);
  jlong result = J2ObjCFpToLong(asDouble);
  if (result != asDouble) {
    @throw new_JavaLangNumberFormatException_initWithNSString_(JreStrcat("$$$I$I$$", @"Expected a long but was ", peekedString_, @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
  peekedString_ = nil;
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
  return result;
}

- (NSString *)nextQuotedValueWithChar:(jchar)quote {
  return ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(self, quote);
}

- (NSString *)nextUnquotedValue {
  return ComGoogleGsonStreamJsonReader_nextUnquotedValue(self);
}

- (void)skipQuotedValueWithChar:(jchar)quote {
  ComGoogleGsonStreamJsonReader_skipQuotedValueWithChar_(self, quote);
}

- (void)skipUnquotedValue {
  ComGoogleGsonStreamJsonReader_skipUnquotedValue(self);
}

- (jint)nextInt {
  jint p = peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(self);
  }
  jint result;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_LONG) {
    result = (jint) peekedLong_;
    if (peekedLong_ != result) {
      @throw new_JavaLangNumberFormatException_initWithNSString_(JreStrcat("$J$I$I$$", @"Expected an int but was ", peekedLong_, @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
    }
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
    (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
    return result;
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NUMBER) {
    peekedString_ = [NSString stringWithCharacters:buffer_ offset:pos_ length:peekedNumberLength_];
    pos_ += peekedNumberLength_;
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED || p == ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED) {
    peekedString_ = ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(self, p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED ? '\'' : '"');
    @try {
      result = JavaLangInteger_parseIntWithNSString_(peekedString_);
      peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
      (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
      return result;
    }
    @catch (JavaLangNumberFormatException *ignored) {
    }
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected an int but was ", [self peek], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_BUFFERED;
  jdouble asDouble = JavaLangDouble_parseDoubleWithNSString_(peekedString_);
  result = J2ObjCFpToInt(asDouble);
  if (result != asDouble) {
    @throw new_JavaLangNumberFormatException_initWithNSString_(JreStrcat("$$$I$I$$", @"Expected an int but was ", peekedString_, @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
  }
  peekedString_ = nil;
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
  return result;
}

- (void)close {
  peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  *IOSIntArray_GetRef(nil_chk(stack_), 0) = ComGoogleGsonStreamJsonScope_CLOSED;
  stackSize_ = 1;
  [((JavaIoReader *) nil_chk(in_)) close];
}

- (void)skipValue {
  jint count = 0;
  do {
    jint p = peeked_;
    if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
      p = ComGoogleGsonStreamJsonReader_doPeek(self);
    }
    if (p == ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_ARRAY) {
      ComGoogleGsonStreamJsonReader_pushWithInt_(self, ComGoogleGsonStreamJsonScope_EMPTY_ARRAY);
      count++;
    }
    else if (p == ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_OBJECT) {
      ComGoogleGsonStreamJsonReader_pushWithInt_(self, ComGoogleGsonStreamJsonScope_EMPTY_OBJECT);
      count++;
    }
    else if (p == ComGoogleGsonStreamJsonReader_PEEKED_END_ARRAY) {
      stackSize_--;
      count--;
    }
    else if (p == ComGoogleGsonStreamJsonReader_PEEKED_END_OBJECT) {
      stackSize_--;
      count--;
    }
    else if (p == ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED_NAME || p == ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED) {
      ComGoogleGsonStreamJsonReader_skipUnquotedValue(self);
    }
    else if (p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED || p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED_NAME) {
      ComGoogleGsonStreamJsonReader_skipQuotedValueWithChar_(self, '\'');
    }
    else if (p == ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED || p == ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED_NAME) {
      ComGoogleGsonStreamJsonReader_skipQuotedValueWithChar_(self, '"');
    }
    else if (p == ComGoogleGsonStreamJsonReader_PEEKED_NUMBER) {
      pos_ += peekedNumberLength_;
    }
    peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  }
  while (count != 0);
  (*IOSIntArray_GetRef(nil_chk(pathIndices_), stackSize_ - 1))++;
  (void) IOSObjectArray_Set(nil_chk(pathNames_), stackSize_ - 1, @"null");
}

- (void)pushWithInt:(jint)newTop {
  ComGoogleGsonStreamJsonReader_pushWithInt_(self, newTop);
}

- (jboolean)fillBufferWithInt:(jint)minimum {
  return ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, minimum);
}

- (jint)getLineNumber {
  return ComGoogleGsonStreamJsonReader_getLineNumber(self);
}

- (jint)getColumnNumber {
  return ComGoogleGsonStreamJsonReader_getColumnNumber(self);
}

- (jint)nextNonWhitespaceWithBoolean:(jboolean)throwOnEof {
  return ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(self, throwOnEof);
}

- (void)checkLenient {
  ComGoogleGsonStreamJsonReader_checkLenient(self);
}

- (void)skipToEndOfLine {
  ComGoogleGsonStreamJsonReader_skipToEndOfLine(self);
}

- (jboolean)skipToWithNSString:(NSString *)toFind {
  return ComGoogleGsonStreamJsonReader_skipToWithNSString_(self, toFind);
}

- (NSString *)description {
  return JreStrcat("$$I$I", [[self getClass] getSimpleName], @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self));
}

- (NSString *)getPath {
  JavaLangStringBuilder *result = [new_JavaLangStringBuilder_init() appendWithChar:'$'];
  for (jint i = 0, size = stackSize_; i < size; i++) {
    switch (IOSIntArray_Get(nil_chk(stack_), i)) {
      case ComGoogleGsonStreamJsonScope_EMPTY_ARRAY:
      case ComGoogleGsonStreamJsonScope_NONEMPTY_ARRAY:
      (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk(result)) appendWithChar:'['])) appendWithInt:IOSIntArray_Get(nil_chk(pathIndices_), i)])) appendWithChar:']'];
      break;
      case ComGoogleGsonStreamJsonScope_EMPTY_OBJECT:
      case ComGoogleGsonStreamJsonScope_DANGLING_NAME:
      case ComGoogleGsonStreamJsonScope_NONEMPTY_OBJECT:
      (void) [((JavaLangStringBuilder *) nil_chk(result)) appendWithChar:'.'];
      if (IOSObjectArray_Get(nil_chk(pathNames_), i) != nil) {
        (void) [result appendWithNSString:IOSObjectArray_Get(pathNames_, i)];
      }
      break;
      case ComGoogleGsonStreamJsonScope_NONEMPTY_DOCUMENT:
      case ComGoogleGsonStreamJsonScope_EMPTY_DOCUMENT:
      case ComGoogleGsonStreamJsonScope_CLOSED:
      break;
    }
  }
  return [((JavaLangStringBuilder *) nil_chk(result)) description];
}

- (jchar)readEscapeCharacter {
  return ComGoogleGsonStreamJsonReader_readEscapeCharacter(self);
}

- (JavaIoIOException *)syntaxErrorWithNSString:(NSString *)message {
  return ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, message);
}

- (void)consumeNonExecutePrefix {
  ComGoogleGsonStreamJsonReader_consumeNonExecutePrefix(self);
}

+ (void)initialize {
  if (self == [ComGoogleGsonStreamJsonReader class]) {
    ComGoogleGsonStreamJsonReader_NON_EXECUTE_PREFIX_ = [@")]}'\n" toCharArray];
    {
      (void) ComGoogleGsonInternalJsonReaderInternalAccess_set_INSTANCE_(new_ComGoogleGsonStreamJsonReader_$1_init());
    }
    J2OBJC_SET_INITIALIZED(ComGoogleGsonStreamJsonReader)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoReader:", "JsonReader", NULL, 0x1, NULL, NULL },
    { "setLenientWithBoolean:", "setLenient", "V", 0x11, NULL, NULL },
    { "isLenient", NULL, "Z", 0x11, NULL, NULL },
    { "beginArray", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
    { "endArray", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
    { "beginObject", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
    { "endObject", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
    { "hasNext", NULL, "Z", 0x1, "Ljava.io.IOException;", NULL },
    { "peek", NULL, "Lcom.google.gson.stream.JsonToken;", 0x1, "Ljava.io.IOException;", NULL },
    { "doPeek", NULL, "I", 0x2, "Ljava.io.IOException;", NULL },
    { "peekKeyword", NULL, "I", 0x2, "Ljava.io.IOException;", NULL },
    { "peekNumber", NULL, "I", 0x2, "Ljava.io.IOException;", NULL },
    { "isLiteralWithChar:", "isLiteral", "Z", 0x2, "Ljava.io.IOException;", NULL },
    { "nextName", NULL, "Ljava.lang.String;", 0x1, "Ljava.io.IOException;", NULL },
    { "nextString", NULL, "Ljava.lang.String;", 0x1, "Ljava.io.IOException;", NULL },
    { "nextBoolean", NULL, "Z", 0x1, "Ljava.io.IOException;", NULL },
    { "nextNull", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
    { "nextDouble", NULL, "D", 0x1, "Ljava.io.IOException;", NULL },
    { "nextLong", NULL, "J", 0x1, "Ljava.io.IOException;", NULL },
    { "nextQuotedValueWithChar:", "nextQuotedValue", "Ljava.lang.String;", 0x2, "Ljava.io.IOException;", NULL },
    { "nextUnquotedValue", NULL, "Ljava.lang.String;", 0x2, "Ljava.io.IOException;", NULL },
    { "skipQuotedValueWithChar:", "skipQuotedValue", "V", 0x2, "Ljava.io.IOException;", NULL },
    { "skipUnquotedValue", NULL, "V", 0x2, "Ljava.io.IOException;", NULL },
    { "nextInt", NULL, "I", 0x1, "Ljava.io.IOException;", NULL },
    { "close", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
    { "skipValue", NULL, "V", 0x1, "Ljava.io.IOException;", NULL },
    { "pushWithInt:", "push", "V", 0x2, NULL, NULL },
    { "fillBufferWithInt:", "fillBuffer", "Z", 0x2, "Ljava.io.IOException;", NULL },
    { "getLineNumber", NULL, "I", 0x2, NULL, NULL },
    { "getColumnNumber", NULL, "I", 0x2, NULL, NULL },
    { "nextNonWhitespaceWithBoolean:", "nextNonWhitespace", "I", 0x2, "Ljava.io.IOException;", NULL },
    { "checkLenient", NULL, "V", 0x2, "Ljava.io.IOException;", NULL },
    { "skipToEndOfLine", NULL, "V", 0x2, "Ljava.io.IOException;", NULL },
    { "skipToWithNSString:", "skipTo", "Z", 0x2, "Ljava.io.IOException;", NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getPath", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "readEscapeCharacter", NULL, "C", 0x2, "Ljava.io.IOException;", NULL },
    { "syntaxErrorWithNSString:", "syntaxError", "Ljava.io.IOException;", 0x2, "Ljava.io.IOException;", NULL },
    { "consumeNonExecutePrefix", NULL, "V", 0x2, "Ljava.io.IOException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NON_EXECUTE_PREFIX_", NULL, 0x1a, "[C", &ComGoogleGsonStreamJsonReader_NON_EXECUTE_PREFIX_, NULL,  },
    { "MIN_INCOMPLETE_INTEGER_", NULL, 0x1a, "J", NULL, NULL, .constantValue.asLong = ComGoogleGsonStreamJsonReader_MIN_INCOMPLETE_INTEGER },
    { "PEEKED_NONE_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_NONE },
    { "PEEKED_BEGIN_OBJECT_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_OBJECT },
    { "PEEKED_END_OBJECT_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_END_OBJECT },
    { "PEEKED_BEGIN_ARRAY_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_ARRAY },
    { "PEEKED_END_ARRAY_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_END_ARRAY },
    { "PEEKED_TRUE_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_TRUE },
    { "PEEKED_FALSE_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_FALSE },
    { "PEEKED_NULL_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_NULL },
    { "PEEKED_SINGLE_QUOTED_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED },
    { "PEEKED_DOUBLE_QUOTED_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED },
    { "PEEKED_UNQUOTED_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED },
    { "PEEKED_BUFFERED_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_BUFFERED },
    { "PEEKED_SINGLE_QUOTED_NAME_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED_NAME },
    { "PEEKED_DOUBLE_QUOTED_NAME_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED_NAME },
    { "PEEKED_UNQUOTED_NAME_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED_NAME },
    { "PEEKED_LONG_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_LONG },
    { "PEEKED_NUMBER_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_NUMBER },
    { "PEEKED_EOF_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_PEEKED_EOF },
    { "NUMBER_CHAR_NONE_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_NONE },
    { "NUMBER_CHAR_SIGN_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_SIGN },
    { "NUMBER_CHAR_DIGIT_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DIGIT },
    { "NUMBER_CHAR_DECIMAL_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DECIMAL },
    { "NUMBER_CHAR_FRACTION_DIGIT_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_FRACTION_DIGIT },
    { "NUMBER_CHAR_EXP_E_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_E },
    { "NUMBER_CHAR_EXP_SIGN_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_SIGN },
    { "NUMBER_CHAR_EXP_DIGIT_", NULL, 0x1a, "I", NULL, NULL, .constantValue.asInt = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_DIGIT },
    { "in_", NULL, 0x12, "Ljava.io.Reader;", NULL, NULL,  },
    { "lenient_", NULL, 0x2, "Z", NULL, NULL,  },
    { "buffer_", NULL, 0x12, "[C", NULL, NULL,  },
    { "pos_", NULL, 0x2, "I", NULL, NULL,  },
    { "limit_", NULL, 0x2, "I", NULL, NULL,  },
    { "lineNumber_", NULL, 0x2, "I", NULL, NULL,  },
    { "lineStart_", NULL, 0x2, "I", NULL, NULL,  },
    { "peeked_", NULL, 0x2, "I", NULL, NULL,  },
    { "peekedLong_", NULL, 0x2, "J", NULL, NULL,  },
    { "peekedNumberLength_", NULL, 0x2, "I", NULL, NULL,  },
    { "peekedString_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL,  },
    { "stack_", NULL, 0x2, "[I", NULL, NULL,  },
    { "stackSize_", NULL, 0x2, "I", NULL, NULL,  },
    { "pathNames_", NULL, 0x2, "[Ljava.lang.String;", NULL, NULL,  },
    { "pathIndices_", NULL, 0x2, "[I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComGoogleGsonStreamJsonReader = { 2, "JsonReader", "com.google.gson.stream", NULL, 0x1, 39, methods, 43, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonStreamJsonReader;
}

@end

void ComGoogleGsonStreamJsonReader_initWithJavaIoReader_(ComGoogleGsonStreamJsonReader *self, JavaIoReader *inArg) {
  (void) NSObject_init(self);
  self->lenient_ = NO;
  self->buffer_ = [IOSCharArray newArrayWithLength:1024];
  self->pos_ = 0;
  self->limit_ = 0;
  self->lineNumber_ = 0;
  self->lineStart_ = 0;
  self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  self->stack_ = [IOSIntArray newArrayWithLength:32];
  self->stackSize_ = 0;
  {
    *IOSIntArray_GetRef(self->stack_, self->stackSize_++) = ComGoogleGsonStreamJsonScope_EMPTY_DOCUMENT;
  }
  self->pathNames_ = [IOSObjectArray newArrayWithLength:32 type:NSString_class_()];
  self->pathIndices_ = [IOSIntArray newArrayWithLength:32];
  if (inArg == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"in == null");
  }
  self->in_ = inArg;
}

ComGoogleGsonStreamJsonReader *new_ComGoogleGsonStreamJsonReader_initWithJavaIoReader_(JavaIoReader *inArg) {
  ComGoogleGsonStreamJsonReader *self = [ComGoogleGsonStreamJsonReader alloc];
  ComGoogleGsonStreamJsonReader_initWithJavaIoReader_(self, inArg);
  return self;
}

jint ComGoogleGsonStreamJsonReader_doPeek(ComGoogleGsonStreamJsonReader *self) {
  jint peekStack = IOSIntArray_Get(nil_chk(self->stack_), self->stackSize_ - 1);
  if (peekStack == ComGoogleGsonStreamJsonScope_EMPTY_ARRAY) {
    *IOSIntArray_GetRef(self->stack_, self->stackSize_ - 1) = ComGoogleGsonStreamJsonScope_NONEMPTY_ARRAY;
  }
  else if (peekStack == ComGoogleGsonStreamJsonScope_NONEMPTY_ARRAY) {
    jint c = ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(self, YES);
    switch (c) {
      case ']':
      return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_END_ARRAY;
      case ';':
      ComGoogleGsonStreamJsonReader_checkLenient(self);
      case ',':
      break;
      default:
      @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Unterminated array");
    }
  }
  else if (peekStack == ComGoogleGsonStreamJsonScope_EMPTY_OBJECT || peekStack == ComGoogleGsonStreamJsonScope_NONEMPTY_OBJECT) {
    *IOSIntArray_GetRef(self->stack_, self->stackSize_ - 1) = ComGoogleGsonStreamJsonScope_DANGLING_NAME;
    if (peekStack == ComGoogleGsonStreamJsonScope_NONEMPTY_OBJECT) {
      jint c = ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(self, YES);
      switch (c) {
        case '}':
        return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_END_OBJECT;
        case ';':
        ComGoogleGsonStreamJsonReader_checkLenient(self);
        case ',':
        break;
        default:
        @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Unterminated object");
      }
    }
    jint c = ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(self, YES);
    switch (c) {
      case '"':
      return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED_NAME;
      case '\'':
      ComGoogleGsonStreamJsonReader_checkLenient(self);
      return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED_NAME;
      case '}':
      if (peekStack != ComGoogleGsonStreamJsonScope_NONEMPTY_OBJECT) {
        return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_END_OBJECT;
      }
      else {
        @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Expected name");
      }
      default:
      ComGoogleGsonStreamJsonReader_checkLenient(self);
      self->pos_--;
      if (ComGoogleGsonStreamJsonReader_isLiteralWithChar_(self, (jchar) c)) {
        return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED_NAME;
      }
      else {
        @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Expected name");
      }
    }
  }
  else if (peekStack == ComGoogleGsonStreamJsonScope_DANGLING_NAME) {
    *IOSIntArray_GetRef(self->stack_, self->stackSize_ - 1) = ComGoogleGsonStreamJsonScope_NONEMPTY_OBJECT;
    jint c = ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(self, YES);
    switch (c) {
      case ':':
      break;
      case '=':
      ComGoogleGsonStreamJsonReader_checkLenient(self);
      if ((self->pos_ < self->limit_ || ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 1)) && IOSCharArray_Get(nil_chk(self->buffer_), self->pos_) == '>') {
        self->pos_++;
      }
      break;
      default:
      @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Expected ':'");
    }
  }
  else if (peekStack == ComGoogleGsonStreamJsonScope_EMPTY_DOCUMENT) {
    if (self->lenient_) {
      ComGoogleGsonStreamJsonReader_consumeNonExecutePrefix(self);
    }
    *IOSIntArray_GetRef(self->stack_, self->stackSize_ - 1) = ComGoogleGsonStreamJsonScope_NONEMPTY_DOCUMENT;
  }
  else if (peekStack == ComGoogleGsonStreamJsonScope_NONEMPTY_DOCUMENT) {
    jint c = ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(self, NO);
    if (c == -1) {
      return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_EOF;
    }
    else {
      ComGoogleGsonStreamJsonReader_checkLenient(self);
      self->pos_--;
    }
  }
  else if (peekStack == ComGoogleGsonStreamJsonScope_CLOSED) {
    @throw new_JavaLangIllegalStateException_initWithNSString_(@"JsonReader is closed");
  }
  jint c = ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(self, YES);
  switch (c) {
    case ']':
    if (peekStack == ComGoogleGsonStreamJsonScope_EMPTY_ARRAY) {
      return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_END_ARRAY;
    }
    case ';':
    case ',':
    if (peekStack == ComGoogleGsonStreamJsonScope_EMPTY_ARRAY || peekStack == ComGoogleGsonStreamJsonScope_NONEMPTY_ARRAY) {
      ComGoogleGsonStreamJsonReader_checkLenient(self);
      self->pos_--;
      return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NULL;
    }
    else {
      @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Unexpected value");
    }
    case '\'':
    ComGoogleGsonStreamJsonReader_checkLenient(self);
    return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED;
    case '"':
    if (self->stackSize_ == 1) {
      ComGoogleGsonStreamJsonReader_checkLenient(self);
    }
    return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED;
    case '[':
    return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_ARRAY;
    case '{':
    return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_BEGIN_OBJECT;
    default:
    self->pos_--;
  }
  if (self->stackSize_ == 1) {
    ComGoogleGsonStreamJsonReader_checkLenient(self);
  }
  jint result = ComGoogleGsonStreamJsonReader_peekKeyword(self);
  if (result != ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    return result;
  }
  result = ComGoogleGsonStreamJsonReader_peekNumber(self);
  if (result != ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    return result;
  }
  if (!ComGoogleGsonStreamJsonReader_isLiteralWithChar_(self, IOSCharArray_Get(nil_chk(self->buffer_), self->pos_))) {
    @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Expected value");
  }
  ComGoogleGsonStreamJsonReader_checkLenient(self);
  return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED;
}

jint ComGoogleGsonStreamJsonReader_peekKeyword(ComGoogleGsonStreamJsonReader *self) {
  jchar c = IOSCharArray_Get(nil_chk(self->buffer_), self->pos_);
  NSString *keyword;
  NSString *keywordUpper;
  jint peeking;
  if (c == 't' || c == 'T') {
    keyword = @"true";
    keywordUpper = @"TRUE";
    peeking = ComGoogleGsonStreamJsonReader_PEEKED_TRUE;
  }
  else if (c == 'f' || c == 'F') {
    keyword = @"false";
    keywordUpper = @"FALSE";
    peeking = ComGoogleGsonStreamJsonReader_PEEKED_FALSE;
  }
  else if (c == 'n' || c == 'N') {
    keyword = @"null";
    keywordUpper = @"NULL";
    peeking = ComGoogleGsonStreamJsonReader_PEEKED_NULL;
  }
  else {
    return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  }
  jint length = ((jint) [((NSString *) nil_chk(keyword)) length]);
  for (jint i = 1; i < length; i++) {
    if (self->pos_ + i >= self->limit_ && !ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, i + 1)) {
      return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
    }
    c = IOSCharArray_Get(self->buffer_, self->pos_ + i);
    if (c != [keyword charAtWithInt:i] && c != [((NSString *) nil_chk(keywordUpper)) charAtWithInt:i]) {
      return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
    }
  }
  if ((self->pos_ + length < self->limit_ || ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, length + 1)) && ComGoogleGsonStreamJsonReader_isLiteralWithChar_(self, IOSCharArray_Get(self->buffer_, self->pos_ + length))) {
    return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  }
  self->pos_ += length;
  return self->peeked_ = peeking;
}

jint ComGoogleGsonStreamJsonReader_peekNumber(ComGoogleGsonStreamJsonReader *self) {
  IOSCharArray *buffer = self->buffer_;
  jint p = self->pos_;
  jint l = self->limit_;
  jlong value = 0;
  jboolean negative = NO;
  jboolean fitsInLong = YES;
  jint last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_NONE;
  jint i = 0;
  for (; YES; i++) {
    if (p + i == l) {
      if (i == ((IOSCharArray *) nil_chk(buffer))->size_) {
        return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
      }
      if (!ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, i + 1)) {
        break;
      }
      p = self->pos_;
      l = self->limit_;
    }
    jchar c = IOSCharArray_Get(nil_chk(buffer), p + i);
    switch (c) {
      case '-':
      if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_NONE) {
        negative = YES;
        last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_SIGN;
        continue;
      }
      else if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_E) {
        last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_SIGN;
        continue;
      }
      return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
      case '+':
      if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_E) {
        last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_SIGN;
        continue;
      }
      return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
      case 'e':
      case 'E':
      if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DIGIT || last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_FRACTION_DIGIT) {
        last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_E;
        continue;
      }
      return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
      case '.':
      if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DIGIT) {
        last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DECIMAL;
        continue;
      }
      return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
      default:
      if (c < '0' || c > '9') {
        if (!ComGoogleGsonStreamJsonReader_isLiteralWithChar_(self, c)) {
          goto break_charactersOfNumber;
        }
        return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
      }
      if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_SIGN || last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_NONE) {
        value = -(c - '0');
        last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DIGIT;
      }
      else if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DIGIT) {
        if (value == 0) {
          return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
        }
        jlong newValue = value * 10 - (c - '0');
        fitsInLong &= (value > ComGoogleGsonStreamJsonReader_MIN_INCOMPLETE_INTEGER || (value == ComGoogleGsonStreamJsonReader_MIN_INCOMPLETE_INTEGER && newValue < value));
        value = newValue;
      }
      else if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DECIMAL) {
        last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_FRACTION_DIGIT;
      }
      else if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_E || last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_SIGN) {
        last = ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_DIGIT;
      }
    }
  }
  break_charactersOfNumber: ;
  if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DIGIT && fitsInLong && (value != JavaLangLong_MIN_VALUE || negative)) {
    self->peekedLong_ = negative ? value : -value;
    self->pos_ += i;
    return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_LONG;
  }
  else if (last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_DIGIT || last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_FRACTION_DIGIT || last == ComGoogleGsonStreamJsonReader_NUMBER_CHAR_EXP_DIGIT) {
    self->peekedNumberLength_ = i;
    return self->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_NUMBER;
  }
  else {
    return ComGoogleGsonStreamJsonReader_PEEKED_NONE;
  }
}

jboolean ComGoogleGsonStreamJsonReader_isLiteralWithChar_(ComGoogleGsonStreamJsonReader *self, jchar c) {
  switch (c) {
    case '/':
    case '\\':
    case ';':
    case '#':
    case '=':
    ComGoogleGsonStreamJsonReader_checkLenient(self);
    case '{':
    case '}':
    case '[':
    case ']':
    case ':':
    case ',':
    case ' ':
    case 0x0009:
    case 0x000c:
    case 0x000d:
    case 0x000a:
    return NO;
    default:
    return YES;
  }
}

NSString *ComGoogleGsonStreamJsonReader_nextQuotedValueWithChar_(ComGoogleGsonStreamJsonReader *self, jchar quote) {
  IOSCharArray *buffer = self->buffer_;
  JavaLangStringBuilder *builder = new_JavaLangStringBuilder_init();
  while (YES) {
    jint p = self->pos_;
    jint l = self->limit_;
    jint start = p;
    while (p < l) {
      jint c = IOSCharArray_Get(nil_chk(buffer), p++);
      if (c == quote) {
        self->pos_ = p;
        (void) [builder appendWithCharArray:buffer withInt:start withInt:p - start - 1];
        return [builder description];
      }
      else if (c == '\\') {
        self->pos_ = p;
        (void) [builder appendWithCharArray:buffer withInt:start withInt:p - start - 1];
        (void) [builder appendWithChar:ComGoogleGsonStreamJsonReader_readEscapeCharacter(self)];
        p = self->pos_;
        l = self->limit_;
        start = p;
      }
      else if (c == 0x000a) {
        self->lineNumber_++;
        self->lineStart_ = p;
      }
    }
    (void) [builder appendWithCharArray:buffer withInt:start withInt:p - start];
    self->pos_ = p;
    if (!ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 1)) {
      @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Unterminated string");
    }
  }
}

NSString *ComGoogleGsonStreamJsonReader_nextUnquotedValue(ComGoogleGsonStreamJsonReader *self) {
  JavaLangStringBuilder *builder = nil;
  jint i = 0;
  while (YES) {
    for (; self->pos_ + i < self->limit_; i++) {
      switch (IOSCharArray_Get(nil_chk(self->buffer_), self->pos_ + i)) {
        case '/':
        case '\\':
        case ';':
        case '#':
        case '=':
        ComGoogleGsonStreamJsonReader_checkLenient(self);
        case '{':
        case '}':
        case '[':
        case ']':
        case ':':
        case ',':
        case ' ':
        case 0x0009:
        case 0x000c:
        case 0x000d:
        case 0x000a:
        goto break_findNonLiteralCharacter;
      }
    }
    if (i < ((IOSCharArray *) nil_chk(self->buffer_))->size_) {
      if (ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, i + 1)) {
        continue;
      }
      else {
        break;
      }
    }
    if (builder == nil) {
      builder = new_JavaLangStringBuilder_init();
    }
    (void) [((JavaLangStringBuilder *) nil_chk(builder)) appendWithCharArray:self->buffer_ withInt:self->pos_ withInt:i];
    self->pos_ += i;
    i = 0;
    if (!ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 1)) {
      break;
    }
  }
  break_findNonLiteralCharacter: ;
  NSString *result;
  if (builder == nil) {
    result = [NSString stringWithCharacters:self->buffer_ offset:self->pos_ length:i];
  }
  else {
    (void) [builder appendWithCharArray:self->buffer_ withInt:self->pos_ withInt:i];
    result = [builder description];
  }
  self->pos_ += i;
  return result;
}

void ComGoogleGsonStreamJsonReader_skipQuotedValueWithChar_(ComGoogleGsonStreamJsonReader *self, jchar quote) {
  IOSCharArray *buffer = self->buffer_;
  do {
    jint p = self->pos_;
    jint l = self->limit_;
    while (p < l) {
      jint c = IOSCharArray_Get(nil_chk(buffer), p++);
      if (c == quote) {
        self->pos_ = p;
        return;
      }
      else if (c == '\\') {
        self->pos_ = p;
        ComGoogleGsonStreamJsonReader_readEscapeCharacter(self);
        p = self->pos_;
        l = self->limit_;
      }
      else if (c == 0x000a) {
        self->lineNumber_++;
        self->lineStart_ = p;
      }
    }
    self->pos_ = p;
  }
  while (ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 1));
  @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Unterminated string");
}

void ComGoogleGsonStreamJsonReader_skipUnquotedValue(ComGoogleGsonStreamJsonReader *self) {
  do {
    jint i = 0;
    for (; self->pos_ + i < self->limit_; i++) {
      switch (IOSCharArray_Get(nil_chk(self->buffer_), self->pos_ + i)) {
        case '/':
        case '\\':
        case ';':
        case '#':
        case '=':
        ComGoogleGsonStreamJsonReader_checkLenient(self);
        case '{':
        case '}':
        case '[':
        case ']':
        case ':':
        case ',':
        case ' ':
        case 0x0009:
        case 0x000c:
        case 0x000d:
        case 0x000a:
        self->pos_ += i;
        return;
      }
    }
    self->pos_ += i;
  }
  while (ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 1));
}

void ComGoogleGsonStreamJsonReader_pushWithInt_(ComGoogleGsonStreamJsonReader *self, jint newTop) {
  if (self->stackSize_ == ((IOSIntArray *) nil_chk(self->stack_))->size_) {
    IOSIntArray *newStack = [IOSIntArray newArrayWithLength:self->stackSize_ * 2];
    IOSIntArray *newPathIndices = [IOSIntArray newArrayWithLength:self->stackSize_ * 2];
    IOSObjectArray *newPathNames = [IOSObjectArray newArrayWithLength:self->stackSize_ * 2 type:NSString_class_()];
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(self->stack_, 0, newStack, 0, self->stackSize_);
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(self->pathIndices_, 0, newPathIndices, 0, self->stackSize_);
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(self->pathNames_, 0, newPathNames, 0, self->stackSize_);
    self->stack_ = newStack;
    self->pathIndices_ = newPathIndices;
    self->pathNames_ = newPathNames;
  }
  *IOSIntArray_GetRef(self->stack_, self->stackSize_++) = newTop;
}

jboolean ComGoogleGsonStreamJsonReader_fillBufferWithInt_(ComGoogleGsonStreamJsonReader *self, jint minimum) {
  IOSCharArray *buffer = self->buffer_;
  self->lineStart_ -= self->pos_;
  if (self->limit_ != self->pos_) {
    self->limit_ -= self->pos_;
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(buffer, self->pos_, buffer, 0, self->limit_);
  }
  else {
    self->limit_ = 0;
  }
  self->pos_ = 0;
  jint total;
  while ((total = [((JavaIoReader *) nil_chk(self->in_)) readWithCharArray:buffer withInt:self->limit_ withInt:((IOSCharArray *) nil_chk(buffer))->size_ - self->limit_]) != -1) {
    self->limit_ += total;
    if (self->lineNumber_ == 0 && self->lineStart_ == 0 && self->limit_ > 0 && IOSCharArray_Get(buffer, 0) == 0xfeff) {
      self->pos_++;
      self->lineStart_++;
      minimum++;
    }
    if (self->limit_ >= minimum) {
      return YES;
    }
  }
  return NO;
}

jint ComGoogleGsonStreamJsonReader_getLineNumber(ComGoogleGsonStreamJsonReader *self) {
  return self->lineNumber_ + 1;
}

jint ComGoogleGsonStreamJsonReader_getColumnNumber(ComGoogleGsonStreamJsonReader *self) {
  return self->pos_ - self->lineStart_ + 1;
}

jint ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(ComGoogleGsonStreamJsonReader *self, jboolean throwOnEof) {
  IOSCharArray *buffer = self->buffer_;
  jint p = self->pos_;
  jint l = self->limit_;
  while (YES) {
    if (p == l) {
      self->pos_ = p;
      if (!ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 1)) {
        break;
      }
      p = self->pos_;
      l = self->limit_;
    }
    jint c = IOSCharArray_Get(nil_chk(buffer), p++);
    if (c == 0x000a) {
      self->lineNumber_++;
      self->lineStart_ = p;
      continue;
    }
    else if (c == ' ' || c == 0x000d || c == 0x0009) {
      continue;
    }
    if (c == '/') {
      self->pos_ = p;
      if (p == l) {
        self->pos_--;
        jboolean charsLoaded = ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 2);
        self->pos_++;
        if (!charsLoaded) {
          return c;
        }
      }
      ComGoogleGsonStreamJsonReader_checkLenient(self);
      jchar peek = IOSCharArray_Get(buffer, self->pos_);
      switch (peek) {
        case '*':
        self->pos_++;
        if (!ComGoogleGsonStreamJsonReader_skipToWithNSString_(self, @"*/")) {
          @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Unterminated comment");
        }
        p = self->pos_ + 2;
        l = self->limit_;
        continue;
        case '/':
        self->pos_++;
        ComGoogleGsonStreamJsonReader_skipToEndOfLine(self);
        p = self->pos_;
        l = self->limit_;
        continue;
        default:
        return c;
      }
    }
    else if (c == '#') {
      self->pos_ = p;
      ComGoogleGsonStreamJsonReader_checkLenient(self);
      ComGoogleGsonStreamJsonReader_skipToEndOfLine(self);
      p = self->pos_;
      l = self->limit_;
    }
    else {
      self->pos_ = p;
      return c;
    }
  }
  if (throwOnEof) {
    @throw new_JavaIoEOFException_initWithNSString_(JreStrcat("$I$I", @"End of input at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self)));
  }
  else {
    return -1;
  }
}

void ComGoogleGsonStreamJsonReader_checkLenient(ComGoogleGsonStreamJsonReader *self) {
  if (!self->lenient_) {
    @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Use JsonReader.setLenient(true) to accept malformed JSON");
  }
}

void ComGoogleGsonStreamJsonReader_skipToEndOfLine(ComGoogleGsonStreamJsonReader *self) {
  while (self->pos_ < self->limit_ || ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 1)) {
    jchar c = IOSCharArray_Get(nil_chk(self->buffer_), self->pos_++);
    if (c == 0x000a) {
      self->lineNumber_++;
      self->lineStart_ = self->pos_;
      break;
    }
    else if (c == 0x000d) {
      break;
    }
  }
}

jboolean ComGoogleGsonStreamJsonReader_skipToWithNSString_(ComGoogleGsonStreamJsonReader *self, NSString *toFind) {
  for (; self->pos_ + ((jint) [((NSString *) nil_chk(toFind)) length]) <= self->limit_ || ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, ((jint) [toFind length])); self->pos_++) {
    {
      if (IOSCharArray_Get(nil_chk(self->buffer_), self->pos_) == 0x000a) {
        self->lineNumber_++;
        self->lineStart_ = self->pos_ + 1;
        continue;
      }
      for (jint c = 0; c < ((jint) [toFind length]); c++) {
        if (IOSCharArray_Get(self->buffer_, self->pos_ + c) != [toFind charAtWithInt:c]) {
          goto continue_outer;
        }
      }
      return YES;
    }
    continue_outer: ;
  }
  return NO;
}

jchar ComGoogleGsonStreamJsonReader_readEscapeCharacter(ComGoogleGsonStreamJsonReader *self) {
  if (self->pos_ == self->limit_ && !ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 1)) {
    @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Unterminated escape sequence");
  }
  jchar escaped = IOSCharArray_Get(nil_chk(self->buffer_), self->pos_++);
  {
    jchar result;
    switch (escaped) {
      case 'u':
      if (self->pos_ + 4 > self->limit_ && !ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, 4)) {
        @throw ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(self, @"Unterminated escape sequence");
      }
      result = 0;
      for (jint i = self->pos_, end = i + 4; i < end; i++) {
        jchar c = IOSCharArray_Get(self->buffer_, i);
        LShiftAssignChar(&result, 4);
        if (c >= '0' && c <= '9') {
          result += (c - '0');
        }
        else if (c >= 'a' && c <= 'f') {
          result += (c - 'a' + 10);
        }
        else if (c >= 'A' && c <= 'F') {
          result += (c - 'A' + 10);
        }
        else {
          @throw new_JavaLangNumberFormatException_initWithNSString_(JreStrcat("$$", @"\\u", [NSString stringWithCharacters:self->buffer_ offset:self->pos_ length:4]));
        }
      }
      self->pos_ += 4;
      return result;
      case 't':
      return 0x0009;
      case 'b':
      return 0x0008;
      case 'n':
      return 0x000a;
      case 'r':
      return 0x000d;
      case 'f':
      return 0x000c;
      case 0x000a:
      self->lineNumber_++;
      self->lineStart_ = self->pos_;
      case '\'':
      case '"':
      case '\\':
      default:
      return escaped;
    }
  }
}

JavaIoIOException *ComGoogleGsonStreamJsonReader_syntaxErrorWithNSString_(ComGoogleGsonStreamJsonReader *self, NSString *message) {
  @throw new_ComGoogleGsonStreamMalformedJsonException_initWithNSString_(JreStrcat("$$I$I$$", message, @" at line ", ComGoogleGsonStreamJsonReader_getLineNumber(self), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(self), @" path ", [self getPath]));
}

void ComGoogleGsonStreamJsonReader_consumeNonExecutePrefix(ComGoogleGsonStreamJsonReader *self) {
  ComGoogleGsonStreamJsonReader_nextNonWhitespaceWithBoolean_(self, YES);
  self->pos_--;
  if (self->pos_ + ((IOSCharArray *) nil_chk(ComGoogleGsonStreamJsonReader_NON_EXECUTE_PREFIX_))->size_ > self->limit_ && !ComGoogleGsonStreamJsonReader_fillBufferWithInt_(self, ComGoogleGsonStreamJsonReader_NON_EXECUTE_PREFIX_->size_)) {
    return;
  }
  for (jint i = 0; i < ComGoogleGsonStreamJsonReader_NON_EXECUTE_PREFIX_->size_; i++) {
    if (IOSCharArray_Get(nil_chk(self->buffer_), self->pos_ + i) != IOSCharArray_Get(ComGoogleGsonStreamJsonReader_NON_EXECUTE_PREFIX_, i)) {
      return;
    }
  }
  self->pos_ += ComGoogleGsonStreamJsonReader_NON_EXECUTE_PREFIX_->size_;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonStreamJsonReader)

@implementation ComGoogleGsonStreamJsonReader_$1

- (void)promoteNameToValueWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader {
  if ([reader isKindOfClass:[ComGoogleGsonInternalBindJsonTreeReader class]]) {
    [((ComGoogleGsonInternalBindJsonTreeReader *) nil_chk(((ComGoogleGsonInternalBindJsonTreeReader *) check_class_cast(reader, [ComGoogleGsonInternalBindJsonTreeReader class])))) promoteNameToValue];
    return;
  }
  jint p = ((ComGoogleGsonStreamJsonReader *) nil_chk(reader))->peeked_;
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_NONE) {
    p = ComGoogleGsonStreamJsonReader_doPeek(reader);
  }
  if (p == ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED_NAME) {
    reader->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_DOUBLE_QUOTED;
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED_NAME) {
    reader->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_SINGLE_QUOTED;
  }
  else if (p == ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED_NAME) {
    reader->peeked_ = ComGoogleGsonStreamJsonReader_PEEKED_UNQUOTED;
  }
  else {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@$I$I$$", @"Expected a name but was ", [reader peek], @"  at line ", ComGoogleGsonStreamJsonReader_getLineNumber(reader), @" column ", ComGoogleGsonStreamJsonReader_getColumnNumber(reader), @" path ", [reader getPath]));
  }
}

- (instancetype)init {
  ComGoogleGsonStreamJsonReader_$1_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "promoteNameToValueWithComGoogleGsonStreamJsonReader:", "promoteNameToValue", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComGoogleGsonStreamJsonReader_$1 = { 2, "", "com.google.gson.stream", "JsonReader", 0x8008, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonStreamJsonReader_$1;
}

@end

void ComGoogleGsonStreamJsonReader_$1_init(ComGoogleGsonStreamJsonReader_$1 *self) {
  (void) ComGoogleGsonInternalJsonReaderInternalAccess_init(self);
}

ComGoogleGsonStreamJsonReader_$1 *new_ComGoogleGsonStreamJsonReader_$1_init() {
  ComGoogleGsonStreamJsonReader_$1 *self = [ComGoogleGsonStreamJsonReader_$1 alloc];
  ComGoogleGsonStreamJsonReader_$1_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonStreamJsonReader_$1)
