//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/internal/Excluder.java
//


#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/google/gson/ExclusionStrategy.h"
#include "com/google/gson/FieldAttributes.h"
#include "com/google/gson/Gson.h"
#include "com/google/gson/TypeAdapter.h"
#include "com/google/gson/annotations/Expose.h"
#include "com/google/gson/annotations/Since.h"
#include "com/google/gson/annotations/Until.h"
#include "com/google/gson/internal/Excluder.h"
#include "com/google/gson/reflect/TypeToken.h"
#include "com/google/gson/stream/JsonReader.h"
#include "com/google/gson/stream/JsonWriter.h"
#include "java/io/IOException.h"
#include "java/lang/AssertionError.h"
#include "java/lang/CloneNotSupportedException.h"
#include "java/lang/Enum.h"
#include "java/lang/reflect/Field.h"
#include "java/lang/reflect/Modifier.h"
#include "java/util/ArrayList.h"
#include "java/util/Collections.h"
#include "java/util/List.h"

#define ComGoogleGsonInternalExcluder_IGNORE_VERSIONS -1.0

@interface ComGoogleGsonInternalExcluder () {
 @public
  jdouble version__;
  jint modifiers_;
  jboolean serializeInnerClasses_;
  jboolean requireExpose_;
  id<JavaUtilList> serializationStrategies_;
  id<JavaUtilList> deserializationStrategies_;
}

- (jboolean)isAnonymousOrLocalWithIOSClass:(IOSClass *)clazz;

- (jboolean)isInnerClassWithIOSClass:(IOSClass *)clazz;

- (jboolean)isStaticWithIOSClass:(IOSClass *)clazz;

- (jboolean)isValidVersionWithComGoogleGsonAnnotationsSince:(id<ComGoogleGsonAnnotationsSince>)since
                          withComGoogleGsonAnnotationsUntil:(id<ComGoogleGsonAnnotationsUntil>)until;

- (jboolean)isValidSinceWithComGoogleGsonAnnotationsSince:(id<ComGoogleGsonAnnotationsSince>)annotation;

- (jboolean)isValidUntilWithComGoogleGsonAnnotationsUntil:(id<ComGoogleGsonAnnotationsUntil>)annotation;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalExcluder, serializationStrategies_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalExcluder, deserializationStrategies_, id<JavaUtilList>)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonInternalExcluder, IGNORE_VERSIONS, jdouble)

__attribute__((unused)) static jboolean ComGoogleGsonInternalExcluder_isAnonymousOrLocalWithIOSClass_(ComGoogleGsonInternalExcluder *self, IOSClass *clazz);

__attribute__((unused)) static jboolean ComGoogleGsonInternalExcluder_isInnerClassWithIOSClass_(ComGoogleGsonInternalExcluder *self, IOSClass *clazz);

__attribute__((unused)) static jboolean ComGoogleGsonInternalExcluder_isStaticWithIOSClass_(ComGoogleGsonInternalExcluder *self, IOSClass *clazz);

__attribute__((unused)) static jboolean ComGoogleGsonInternalExcluder_isValidVersionWithComGoogleGsonAnnotationsSince_withComGoogleGsonAnnotationsUntil_(ComGoogleGsonInternalExcluder *self, id<ComGoogleGsonAnnotationsSince> since, id<ComGoogleGsonAnnotationsUntil> until);

__attribute__((unused)) static jboolean ComGoogleGsonInternalExcluder_isValidSinceWithComGoogleGsonAnnotationsSince_(ComGoogleGsonInternalExcluder *self, id<ComGoogleGsonAnnotationsSince> annotation);

__attribute__((unused)) static jboolean ComGoogleGsonInternalExcluder_isValidUntilWithComGoogleGsonAnnotationsUntil_(ComGoogleGsonInternalExcluder *self, id<ComGoogleGsonAnnotationsUntil> annotation);

@interface ComGoogleGsonInternalExcluder_$1 : ComGoogleGsonTypeAdapter {
 @public
  ComGoogleGsonInternalExcluder *this$0_;
  ComGoogleGsonTypeAdapter *delegate__;
  jboolean val$skipDeserialize_;
  jboolean val$skipSerialize_;
  ComGoogleGsonGson *val$gson_;
  ComGoogleGsonReflectTypeToken *val$type_;
}

- (id)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(id)value;

- (ComGoogleGsonTypeAdapter *)delegate;

- (instancetype)initWithComGoogleGsonInternalExcluder:(ComGoogleGsonInternalExcluder *)outer$
                                          withBoolean:(jboolean)capture$0
                                          withBoolean:(jboolean)capture$1
                                withComGoogleGsonGson:(ComGoogleGsonGson *)capture$2
                    withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)capture$3;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalExcluder_$1)

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalExcluder_$1, this$0_, ComGoogleGsonInternalExcluder *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalExcluder_$1, delegate__, ComGoogleGsonTypeAdapter *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalExcluder_$1, val$gson_, ComGoogleGsonGson *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalExcluder_$1, val$type_, ComGoogleGsonReflectTypeToken *)

__attribute__((unused)) static ComGoogleGsonTypeAdapter *ComGoogleGsonInternalExcluder_$1_delegate(ComGoogleGsonInternalExcluder_$1 *self);

__attribute__((unused)) static void ComGoogleGsonInternalExcluder_$1_initWithComGoogleGsonInternalExcluder_withBoolean_withBoolean_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_(ComGoogleGsonInternalExcluder_$1 *self, ComGoogleGsonInternalExcluder *outer$, jboolean capture$0, jboolean capture$1, ComGoogleGsonGson *capture$2, ComGoogleGsonReflectTypeToken *capture$3);

__attribute__((unused)) static ComGoogleGsonInternalExcluder_$1 *new_ComGoogleGsonInternalExcluder_$1_initWithComGoogleGsonInternalExcluder_withBoolean_withBoolean_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_(ComGoogleGsonInternalExcluder *outer$, jboolean capture$0, jboolean capture$1, ComGoogleGsonGson *capture$2, ComGoogleGsonReflectTypeToken *capture$3) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalExcluder_$1)

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonInternalExcluder)

ComGoogleGsonInternalExcluder *ComGoogleGsonInternalExcluder_DEFAULT_;

@implementation ComGoogleGsonInternalExcluder

- (ComGoogleGsonInternalExcluder *)clone {
  @try {
    return (ComGoogleGsonInternalExcluder *) check_class_cast([super clone], [ComGoogleGsonInternalExcluder class]);
  }
  @catch (JavaLangCloneNotSupportedException *e) {
    @throw new_JavaLangAssertionError_init();
  }
}

- (ComGoogleGsonInternalExcluder *)withVersionWithDouble:(jdouble)ignoreVersionsAfter {
  ComGoogleGsonInternalExcluder *result = [self clone];
  ((ComGoogleGsonInternalExcluder *) nil_chk(result))->version__ = ignoreVersionsAfter;
  return result;
}

- (ComGoogleGsonInternalExcluder *)withModifiersWithIntArray:(IOSIntArray *)modifiers {
  ComGoogleGsonInternalExcluder *result = [self clone];
  ((ComGoogleGsonInternalExcluder *) nil_chk(result))->modifiers_ = 0;
  {
    IOSIntArray *a__ = modifiers;
    jint const *b__ = ((IOSIntArray *) nil_chk(a__))->buffer_;
    jint const *e__ = b__ + a__->size_;
    while (b__ < e__) {
      jint modifier = *b__++;
      result->modifiers_ |= modifier;
    }
  }
  return result;
}

- (ComGoogleGsonInternalExcluder *)disableInnerClassSerialization {
  ComGoogleGsonInternalExcluder *result = [self clone];
  ((ComGoogleGsonInternalExcluder *) nil_chk(result))->serializeInnerClasses_ = NO;
  return result;
}

- (ComGoogleGsonInternalExcluder *)excludeFieldsWithoutExposeAnnotation {
  ComGoogleGsonInternalExcluder *result = [self clone];
  ((ComGoogleGsonInternalExcluder *) nil_chk(result))->requireExpose_ = YES;
  return result;
}

- (ComGoogleGsonInternalExcluder *)withExclusionStrategyWithComGoogleGsonExclusionStrategy:(id<ComGoogleGsonExclusionStrategy>)exclusionStrategy
                                                                               withBoolean:(jboolean)serialization
                                                                               withBoolean:(jboolean)deserialization {
  ComGoogleGsonInternalExcluder *result = [self clone];
  if (serialization) {
    ((ComGoogleGsonInternalExcluder *) nil_chk(result))->serializationStrategies_ = new_JavaUtilArrayList_initWithJavaUtilCollection_(serializationStrategies_);
    [result->serializationStrategies_ addWithId:exclusionStrategy];
  }
  if (deserialization) {
    ((ComGoogleGsonInternalExcluder *) nil_chk(result))->deserializationStrategies_ = new_JavaUtilArrayList_initWithJavaUtilCollection_(deserializationStrategies_);
    [result->deserializationStrategies_ addWithId:exclusionStrategy];
  }
  return result;
}

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type {
  IOSClass *rawType = [((ComGoogleGsonReflectTypeToken *) nil_chk(type)) getRawType];
  jboolean skipSerialize = [self excludeClassWithIOSClass:rawType withBoolean:YES];
  jboolean skipDeserialize = [self excludeClassWithIOSClass:rawType withBoolean:NO];
  if (!skipSerialize && !skipDeserialize) {
    return nil;
  }
  return new_ComGoogleGsonInternalExcluder_$1_initWithComGoogleGsonInternalExcluder_withBoolean_withBoolean_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_(self, skipDeserialize, skipSerialize, gson, type);
}

- (jboolean)excludeFieldWithJavaLangReflectField:(JavaLangReflectField *)field
                                     withBoolean:(jboolean)serialize {
  if ((modifiers_ & [((JavaLangReflectField *) nil_chk(field)) getModifiers]) != 0) {
    return YES;
  }
  if (version__ != ComGoogleGsonInternalExcluder_IGNORE_VERSIONS && !ComGoogleGsonInternalExcluder_isValidVersionWithComGoogleGsonAnnotationsSince_withComGoogleGsonAnnotationsUntil_(self, [field getAnnotationWithIOSClass:ComGoogleGsonAnnotationsSince_class_()], [field getAnnotationWithIOSClass:ComGoogleGsonAnnotationsUntil_class_()])) {
    return YES;
  }
  if ([field isSynthetic]) {
    return YES;
  }
  if (requireExpose_) {
    id<ComGoogleGsonAnnotationsExpose> annotation = [field getAnnotationWithIOSClass:ComGoogleGsonAnnotationsExpose_class_()];
    if (annotation == nil || (serialize ? ![annotation serialize] : ![annotation deserialize])) {
      return YES;
    }
  }
  if (!serializeInnerClasses_ && ComGoogleGsonInternalExcluder_isInnerClassWithIOSClass_(self, [field getType])) {
    return YES;
  }
  if (ComGoogleGsonInternalExcluder_isAnonymousOrLocalWithIOSClass_(self, [field getType])) {
    return YES;
  }
  id<JavaUtilList> list = serialize ? serializationStrategies_ : deserializationStrategies_;
  if (![list isEmpty]) {
    ComGoogleGsonFieldAttributes *fieldAttributes = new_ComGoogleGsonFieldAttributes_initWithJavaLangReflectField_(field);
    for (id<ComGoogleGsonExclusionStrategy> __strong exclusionStrategy in list) {
      if ([((id<ComGoogleGsonExclusionStrategy>) nil_chk(exclusionStrategy)) shouldSkipFieldWithComGoogleGsonFieldAttributes:fieldAttributes]) {
        return YES;
      }
    }
  }
  return NO;
}

- (jboolean)excludeClassWithIOSClass:(IOSClass *)clazz
                         withBoolean:(jboolean)serialize {
  if (version__ != ComGoogleGsonInternalExcluder_IGNORE_VERSIONS && !ComGoogleGsonInternalExcluder_isValidVersionWithComGoogleGsonAnnotationsSince_withComGoogleGsonAnnotationsUntil_(self, [((IOSClass *) nil_chk(clazz)) getAnnotationWithIOSClass:ComGoogleGsonAnnotationsSince_class_()], [clazz getAnnotationWithIOSClass:ComGoogleGsonAnnotationsUntil_class_()])) {
    return YES;
  }
  if (!serializeInnerClasses_ && ComGoogleGsonInternalExcluder_isInnerClassWithIOSClass_(self, clazz)) {
    return YES;
  }
  if (ComGoogleGsonInternalExcluder_isAnonymousOrLocalWithIOSClass_(self, clazz)) {
    return YES;
  }
  id<JavaUtilList> list = serialize ? serializationStrategies_ : deserializationStrategies_;
  for (id<ComGoogleGsonExclusionStrategy> __strong exclusionStrategy in list) {
    if ([((id<ComGoogleGsonExclusionStrategy>) nil_chk(exclusionStrategy)) shouldSkipClassWithIOSClass:clazz]) {
      return YES;
    }
  }
  return NO;
}

- (jboolean)isAnonymousOrLocalWithIOSClass:(IOSClass *)clazz {
  return ComGoogleGsonInternalExcluder_isAnonymousOrLocalWithIOSClass_(self, clazz);
}

- (jboolean)isInnerClassWithIOSClass:(IOSClass *)clazz {
  return ComGoogleGsonInternalExcluder_isInnerClassWithIOSClass_(self, clazz);
}

- (jboolean)isStaticWithIOSClass:(IOSClass *)clazz {
  return ComGoogleGsonInternalExcluder_isStaticWithIOSClass_(self, clazz);
}

- (jboolean)isValidVersionWithComGoogleGsonAnnotationsSince:(id<ComGoogleGsonAnnotationsSince>)since
                          withComGoogleGsonAnnotationsUntil:(id<ComGoogleGsonAnnotationsUntil>)until {
  return ComGoogleGsonInternalExcluder_isValidVersionWithComGoogleGsonAnnotationsSince_withComGoogleGsonAnnotationsUntil_(self, since, until);
}

- (jboolean)isValidSinceWithComGoogleGsonAnnotationsSince:(id<ComGoogleGsonAnnotationsSince>)annotation {
  return ComGoogleGsonInternalExcluder_isValidSinceWithComGoogleGsonAnnotationsSince_(self, annotation);
}

- (jboolean)isValidUntilWithComGoogleGsonAnnotationsUntil:(id<ComGoogleGsonAnnotationsUntil>)annotation {
  return ComGoogleGsonInternalExcluder_isValidUntilWithComGoogleGsonAnnotationsUntil_(self, annotation);
}

- (instancetype)init {
  ComGoogleGsonInternalExcluder_init(self);
  return self;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self clone];
}

+ (void)initialize {
  if (self == [ComGoogleGsonInternalExcluder class]) {
    ComGoogleGsonInternalExcluder_DEFAULT_ = new_ComGoogleGsonInternalExcluder_init();
    J2OBJC_SET_INITIALIZED(ComGoogleGsonInternalExcluder)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "clone", NULL, "Lcom.google.gson.internal.Excluder;", 0x4, NULL, NULL },
    { "withVersionWithDouble:", "withVersion", "Lcom.google.gson.internal.Excluder;", 0x1, NULL, NULL },
    { "withModifiersWithIntArray:", "withModifiers", "Lcom.google.gson.internal.Excluder;", 0x81, NULL, NULL },
    { "disableInnerClassSerialization", NULL, "Lcom.google.gson.internal.Excluder;", 0x1, NULL, NULL },
    { "excludeFieldsWithoutExposeAnnotation", NULL, "Lcom.google.gson.internal.Excluder;", 0x1, NULL, NULL },
    { "withExclusionStrategyWithComGoogleGsonExclusionStrategy:withBoolean:withBoolean:", "withExclusionStrategy", "Lcom.google.gson.internal.Excluder;", 0x1, NULL, NULL },
    { "createWithComGoogleGsonGson:withComGoogleGsonReflectTypeToken:", "create", "Lcom.google.gson.TypeAdapter;", 0x1, NULL, "<T:Ljava/lang/Object;>(Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
    { "excludeFieldWithJavaLangReflectField:withBoolean:", "excludeField", "Z", 0x1, NULL, NULL },
    { "excludeClassWithIOSClass:withBoolean:", "excludeClass", "Z", 0x1, NULL, NULL },
    { "isAnonymousOrLocalWithIOSClass:", "isAnonymousOrLocal", "Z", 0x2, NULL, NULL },
    { "isInnerClassWithIOSClass:", "isInnerClass", "Z", 0x2, NULL, NULL },
    { "isStaticWithIOSClass:", "isStatic", "Z", 0x2, NULL, NULL },
    { "isValidVersionWithComGoogleGsonAnnotationsSince:withComGoogleGsonAnnotationsUntil:", "isValidVersion", "Z", 0x2, NULL, NULL },
    { "isValidSinceWithComGoogleGsonAnnotationsSince:", "isValidSince", "Z", 0x2, NULL, NULL },
    { "isValidUntilWithComGoogleGsonAnnotationsUntil:", "isValidUntil", "Z", 0x2, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "IGNORE_VERSIONS_", NULL, 0x1a, "D", NULL, NULL, .constantValue.asDouble = ComGoogleGsonInternalExcluder_IGNORE_VERSIONS },
    { "DEFAULT_", NULL, 0x19, "Lcom.google.gson.internal.Excluder;", &ComGoogleGsonInternalExcluder_DEFAULT_, NULL,  },
    { "version__", "version", 0x2, "D", NULL, NULL,  },
    { "modifiers_", NULL, 0x2, "I", NULL, NULL,  },
    { "serializeInnerClasses_", NULL, 0x2, "Z", NULL, NULL,  },
    { "requireExpose_", NULL, 0x2, "Z", NULL, NULL,  },
    { "serializationStrategies_", NULL, 0x2, "Ljava.util.List;", NULL, "Ljava/util/List<Lcom/google/gson/ExclusionStrategy;>;",  },
    { "deserializationStrategies_", NULL, 0x2, "Ljava.util.List;", NULL, "Ljava/util/List<Lcom/google/gson/ExclusionStrategy;>;",  },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalExcluder = { 2, "Excluder", "com.google.gson.internal", NULL, 0x11, 16, methods, 8, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonInternalExcluder;
}

@end

jboolean ComGoogleGsonInternalExcluder_isAnonymousOrLocalWithIOSClass_(ComGoogleGsonInternalExcluder *self, IOSClass *clazz) {
  return ![JavaLangEnum_class_() isAssignableFrom:clazz] && ([((IOSClass *) nil_chk(clazz)) isAnonymousClass] || [clazz isLocalClass]);
}

jboolean ComGoogleGsonInternalExcluder_isInnerClassWithIOSClass_(ComGoogleGsonInternalExcluder *self, IOSClass *clazz) {
  return [((IOSClass *) nil_chk(clazz)) isMemberClass] && !ComGoogleGsonInternalExcluder_isStaticWithIOSClass_(self, clazz);
}

jboolean ComGoogleGsonInternalExcluder_isStaticWithIOSClass_(ComGoogleGsonInternalExcluder *self, IOSClass *clazz) {
  return ([((IOSClass *) nil_chk(clazz)) getModifiers] & JavaLangReflectModifier_STATIC) != 0;
}

jboolean ComGoogleGsonInternalExcluder_isValidVersionWithComGoogleGsonAnnotationsSince_withComGoogleGsonAnnotationsUntil_(ComGoogleGsonInternalExcluder *self, id<ComGoogleGsonAnnotationsSince> since, id<ComGoogleGsonAnnotationsUntil> until) {
  return ComGoogleGsonInternalExcluder_isValidSinceWithComGoogleGsonAnnotationsSince_(self, since) && ComGoogleGsonInternalExcluder_isValidUntilWithComGoogleGsonAnnotationsUntil_(self, until);
}

jboolean ComGoogleGsonInternalExcluder_isValidSinceWithComGoogleGsonAnnotationsSince_(ComGoogleGsonInternalExcluder *self, id<ComGoogleGsonAnnotationsSince> annotation) {
  if (annotation != nil) {
    jdouble annotationVersion = [annotation value];
    if (annotationVersion > self->version__) {
      return NO;
    }
  }
  return YES;
}

jboolean ComGoogleGsonInternalExcluder_isValidUntilWithComGoogleGsonAnnotationsUntil_(ComGoogleGsonInternalExcluder *self, id<ComGoogleGsonAnnotationsUntil> annotation) {
  if (annotation != nil) {
    jdouble annotationVersion = [annotation value];
    if (annotationVersion <= self->version__) {
      return NO;
    }
  }
  return YES;
}

void ComGoogleGsonInternalExcluder_init(ComGoogleGsonInternalExcluder *self) {
  (void) NSObject_init(self);
  self->version__ = ComGoogleGsonInternalExcluder_IGNORE_VERSIONS;
  self->modifiers_ = JavaLangReflectModifier_TRANSIENT | JavaLangReflectModifier_STATIC;
  self->serializeInnerClasses_ = YES;
  self->serializationStrategies_ = JavaUtilCollections_emptyList();
  self->deserializationStrategies_ = JavaUtilCollections_emptyList();
}

ComGoogleGsonInternalExcluder *new_ComGoogleGsonInternalExcluder_init() {
  ComGoogleGsonInternalExcluder *self = [ComGoogleGsonInternalExcluder alloc];
  ComGoogleGsonInternalExcluder_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalExcluder)

@implementation ComGoogleGsonInternalExcluder_$1

- (id)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg {
  if (val$skipDeserialize_) {
    [((ComGoogleGsonStreamJsonReader *) nil_chk(inArg)) skipValue];
    return nil;
  }
  return [((ComGoogleGsonTypeAdapter *) nil_chk(ComGoogleGsonInternalExcluder_$1_delegate(self))) readWithComGoogleGsonStreamJsonReader:inArg];
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(id)value {
  if (val$skipSerialize_) {
    (void) [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  [((ComGoogleGsonTypeAdapter *) nil_chk(ComGoogleGsonInternalExcluder_$1_delegate(self))) writeWithComGoogleGsonStreamJsonWriter:outArg withId:value];
}

- (ComGoogleGsonTypeAdapter *)delegate {
  return ComGoogleGsonInternalExcluder_$1_delegate(self);
}

- (instancetype)initWithComGoogleGsonInternalExcluder:(ComGoogleGsonInternalExcluder *)outer$
                                          withBoolean:(jboolean)capture$0
                                          withBoolean:(jboolean)capture$1
                                withComGoogleGsonGson:(ComGoogleGsonGson *)capture$2
                    withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)capture$3 {
  ComGoogleGsonInternalExcluder_$1_initWithComGoogleGsonInternalExcluder_withBoolean_withBoolean_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_(self, outer$, capture$0, capture$1, capture$2, capture$3);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "readWithComGoogleGsonStreamJsonReader:", "read", "TT;", 0x1, "Ljava.io.IOException;", "(Lcom/google/gson/stream/JsonReader;)TT;" },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", "(Lcom/google/gson/stream/JsonWriter;TT;)V" },
    { "delegate", NULL, "Lcom.google.gson.TypeAdapter;", 0x2, NULL, NULL },
    { "initWithComGoogleGsonInternalExcluder:withBoolean:withBoolean:withComGoogleGsonGson:withComGoogleGsonReflectTypeToken:", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.Excluder;", NULL, NULL,  },
    { "delegate__", "delegate", 0x2, "Lcom.google.gson.TypeAdapter;", NULL, "Lcom/google/gson/TypeAdapter<TT;>;",  },
    { "val$skipDeserialize_", NULL, 0x1012, "Z", NULL, NULL,  },
    { "val$skipSerialize_", NULL, 0x1012, "Z", NULL, NULL,  },
    { "val$gson_", NULL, 0x1012, "Lcom.google.gson.Gson;", NULL, NULL,  },
    { "val$type_", NULL, 0x1012, "Lcom.google.gson.reflect.TypeToken;", NULL, "Lcom/google/gson/reflect/TypeToken<TT;>;",  },
  };
  static const char *superclass_type_args[] = {"TT;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonInternalExcluder", "createWithComGoogleGsonGson:withComGoogleGsonReflectTypeToken:" };
  static const J2ObjcClassInfo _ComGoogleGsonInternalExcluder_$1 = { 2, "", "com.google.gson.internal", "Excluder", 0x8008, 4, methods, 6, fields, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/TypeAdapter<TT;>;" };
  return &_ComGoogleGsonInternalExcluder_$1;
}

@end

ComGoogleGsonTypeAdapter *ComGoogleGsonInternalExcluder_$1_delegate(ComGoogleGsonInternalExcluder_$1 *self) {
  ComGoogleGsonTypeAdapter *d = self->delegate__;
  return d != nil ? d : (self->delegate__ = [((ComGoogleGsonGson *) nil_chk(self->val$gson_)) getDelegateAdapterWithComGoogleGsonTypeAdapterFactory:self->this$0_ withComGoogleGsonReflectTypeToken:self->val$type_]);
}

void ComGoogleGsonInternalExcluder_$1_initWithComGoogleGsonInternalExcluder_withBoolean_withBoolean_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_(ComGoogleGsonInternalExcluder_$1 *self, ComGoogleGsonInternalExcluder *outer$, jboolean capture$0, jboolean capture$1, ComGoogleGsonGson *capture$2, ComGoogleGsonReflectTypeToken *capture$3) {
  self->this$0_ = outer$;
  self->val$skipDeserialize_ = capture$0;
  self->val$skipSerialize_ = capture$1;
  self->val$gson_ = capture$2;
  self->val$type_ = capture$3;
  (void) ComGoogleGsonTypeAdapter_init(self);
}

ComGoogleGsonInternalExcluder_$1 *new_ComGoogleGsonInternalExcluder_$1_initWithComGoogleGsonInternalExcluder_withBoolean_withBoolean_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_(ComGoogleGsonInternalExcluder *outer$, jboolean capture$0, jboolean capture$1, ComGoogleGsonGson *capture$2, ComGoogleGsonReflectTypeToken *capture$3) {
  ComGoogleGsonInternalExcluder_$1 *self = [ComGoogleGsonInternalExcluder_$1 alloc];
  ComGoogleGsonInternalExcluder_$1_initWithComGoogleGsonInternalExcluder_withBoolean_withBoolean_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_(self, outer$, capture$0, capture$1, capture$2, capture$3);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalExcluder_$1)
