//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/internal/LinkedTreeMap.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/google/gson/internal/LinkedTreeMap.h"
#include "java/io/ObjectStreamException.h"
#include "java/lang/ClassCastException.h"
#include "java/lang/Comparable.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/Math.h"
#include "java/lang/NullPointerException.h"
#include "java/util/AbstractMap.h"
#include "java/util/AbstractSet.h"
#include "java/util/Comparator.h"
#include "java/util/ConcurrentModificationException.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/Map.h"
#include "java/util/NoSuchElementException.h"
#include "java/util/Set.h"

#pragma clang diagnostic ignored "-Wprotocol"

@interface ComGoogleGsonInternalLinkedTreeMap () {
 @public
  ComGoogleGsonInternalLinkedTreeMap_EntrySet *entrySet__;
  ComGoogleGsonInternalLinkedTreeMap_KeySet *keySet_LinkedTreeMap_;
}

- (jboolean)equalWithId:(id)a
                 withId:(id)b;

- (void)replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)node
                       withComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)replacement;

- (void)rebalanceWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)unbalanced
                                                 withBoolean:(jboolean)insert;

- (void)rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)root;

- (void)rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)root;

- (id)writeReplace;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedTreeMap, entrySet__, ComGoogleGsonInternalLinkedTreeMap_EntrySet *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedTreeMap, keySet_LinkedTreeMap_, ComGoogleGsonInternalLinkedTreeMap_KeySet *)

static id<JavaUtilComparator> ComGoogleGsonInternalLinkedTreeMap_NATURAL_ORDER_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonInternalLinkedTreeMap, NATURAL_ORDER_, id<JavaUtilComparator>)

__attribute__((unused)) static jboolean ComGoogleGsonInternalLinkedTreeMap_equalWithId_withId_(ComGoogleGsonInternalLinkedTreeMap *self, id a, id b);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(ComGoogleGsonInternalLinkedTreeMap *self, ComGoogleGsonInternalLinkedTreeMap_Node *node, ComGoogleGsonInternalLinkedTreeMap_Node *replacement);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedTreeMap_rebalanceWithComGoogleGsonInternalLinkedTreeMap_Node_withBoolean_(ComGoogleGsonInternalLinkedTreeMap *self, ComGoogleGsonInternalLinkedTreeMap_Node *unbalanced, jboolean insert);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedTreeMap_rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node_(ComGoogleGsonInternalLinkedTreeMap *self, ComGoogleGsonInternalLinkedTreeMap_Node *root);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedTreeMap_rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node_(ComGoogleGsonInternalLinkedTreeMap *self, ComGoogleGsonInternalLinkedTreeMap_Node *root);

@interface ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator : NSObject < JavaUtilIterator > {
 @public
  ComGoogleGsonInternalLinkedTreeMap *this$0_;
  ComGoogleGsonInternalLinkedTreeMap_Node *next_;
  ComGoogleGsonInternalLinkedTreeMap_Node *lastReturned_;
  jint expectedModCount_;
}

- (jboolean)hasNext;

- (ComGoogleGsonInternalLinkedTreeMap_Node *)nextNode;

- (void)remove;

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap:(ComGoogleGsonInternalLinkedTreeMap *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator)

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator, this$0_, ComGoogleGsonInternalLinkedTreeMap *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator, next_, ComGoogleGsonInternalLinkedTreeMap_Node *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator, lastReturned_, ComGoogleGsonInternalLinkedTreeMap_Node *)

__attribute__((unused)) static ComGoogleGsonInternalLinkedTreeMap_Node *ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator *self);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedTreeMap_(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator *self, ComGoogleGsonInternalLinkedTreeMap *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator)

@interface ComGoogleGsonInternalLinkedTreeMap_EntrySet () {
 @public
  ComGoogleGsonInternalLinkedTreeMap *this$0_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedTreeMap_EntrySet, this$0_, ComGoogleGsonInternalLinkedTreeMap *)

@interface ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1 : ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator

- (id<JavaUtilMap_Entry>)next;

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap_EntrySet:(ComGoogleGsonInternalLinkedTreeMap_EntrySet *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1)

__attribute__((unused)) static void ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_EntrySet_(ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1 *self, ComGoogleGsonInternalLinkedTreeMap_EntrySet *outer$);

__attribute__((unused)) static ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1 *new_ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_EntrySet_(ComGoogleGsonInternalLinkedTreeMap_EntrySet *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1)

@interface ComGoogleGsonInternalLinkedTreeMap_KeySet () {
 @public
  ComGoogleGsonInternalLinkedTreeMap *this$0_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedTreeMap_KeySet, this$0_, ComGoogleGsonInternalLinkedTreeMap *)

@interface ComGoogleGsonInternalLinkedTreeMap_KeySet_$1 : ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator

- (id)next;

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap_KeySet:(ComGoogleGsonInternalLinkedTreeMap_KeySet *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedTreeMap_KeySet_$1)

__attribute__((unused)) static void ComGoogleGsonInternalLinkedTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_KeySet_(ComGoogleGsonInternalLinkedTreeMap_KeySet_$1 *self, ComGoogleGsonInternalLinkedTreeMap_KeySet *outer$);

__attribute__((unused)) static ComGoogleGsonInternalLinkedTreeMap_KeySet_$1 *new_ComGoogleGsonInternalLinkedTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_KeySet_(ComGoogleGsonInternalLinkedTreeMap_KeySet *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedTreeMap_KeySet_$1)

@interface ComGoogleGsonInternalLinkedTreeMap_$1 : NSObject < JavaUtilComparator >

- (jint)compareWithId:(id<JavaLangComparable>)a
               withId:(id<JavaLangComparable>)b;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedTreeMap_$1)

__attribute__((unused)) static void ComGoogleGsonInternalLinkedTreeMap_$1_init(ComGoogleGsonInternalLinkedTreeMap_$1 *self);

__attribute__((unused)) static ComGoogleGsonInternalLinkedTreeMap_$1 *new_ComGoogleGsonInternalLinkedTreeMap_$1_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedTreeMap_$1)

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonInternalLinkedTreeMap)

@implementation ComGoogleGsonInternalLinkedTreeMap

- (instancetype)init {
  ComGoogleGsonInternalLinkedTreeMap_init(self);
  return self;
}

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator {
  ComGoogleGsonInternalLinkedTreeMap_initWithJavaUtilComparator_(self, comparator);
  return self;
}

- (jint)size {
  return size__;
}

- (id)getWithId:(id)key {
  ComGoogleGsonInternalLinkedTreeMap_Node *node = [self findByObjectWithId:key];
  return node != nil ? node->value_ : nil;
}

- (jboolean)containsKeyWithId:(id)key {
  return [self findByObjectWithId:key] != nil;
}

- (id)putWithId:(id)key
         withId:(id)value {
  if (key == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"key == null");
  }
  ComGoogleGsonInternalLinkedTreeMap_Node *created = [self findWithId:key withBoolean:YES];
  id result = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(created))->value_;
  created->value_ = value;
  return result;
}

- (void)clear {
  root_ = nil;
  size__ = 0;
  modCount_++;
  ComGoogleGsonInternalLinkedTreeMap_Node *header = self->header_;
  ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(header))->next_ = header->prev_ = header;
}

- (id)removeWithId:(id)key {
  ComGoogleGsonInternalLinkedTreeMap_Node *node = [self removeInternalByKeyWithId:key];
  return node != nil ? node->value_ : nil;
}

- (ComGoogleGsonInternalLinkedTreeMap_Node *)findWithId:(id)key
                                            withBoolean:(jboolean)create {
  id<JavaUtilComparator> comparator = self->comparator_;
  ComGoogleGsonInternalLinkedTreeMap_Node *nearest = root_;
  jint comparison = 0;
  if (nearest != nil) {
    id<JavaLangComparable> comparableKey = (comparator == ComGoogleGsonInternalLinkedTreeMap_NATURAL_ORDER_) ? (id<JavaLangComparable>) check_protocol_cast(key, @protocol(JavaLangComparable)) : nil;
    while (YES) {
      comparison = (comparableKey != nil) ? [comparableKey compareToWithId:nearest->key_] : [((id<JavaUtilComparator>) nil_chk(comparator)) compareWithId:key withId:nearest->key_];
      if (comparison == 0) {
        return nearest;
      }
      ComGoogleGsonInternalLinkedTreeMap_Node *child = (comparison < 0) ? nearest->left_ : nearest->right_;
      if (child == nil) {
        break;
      }
      nearest = child;
    }
  }
  if (!create) {
    return nil;
  }
  ComGoogleGsonInternalLinkedTreeMap_Node *header = self->header_;
  ComGoogleGsonInternalLinkedTreeMap_Node *created;
  if (nearest == nil) {
    if (comparator == ComGoogleGsonInternalLinkedTreeMap_NATURAL_ORDER_ && !([JavaLangComparable_class_() isInstance:key])) {
      @throw new_JavaLangClassCastException_initWithNSString_(JreStrcat("$$", [[nil_chk(key) getClass] getName], @" is not Comparable"));
    }
    created = new_ComGoogleGsonInternalLinkedTreeMap_Node_initWithComGoogleGsonInternalLinkedTreeMap_Node_withId_withComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(nearest, key, header, ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(header))->prev_);
    root_ = created;
  }
  else {
    created = new_ComGoogleGsonInternalLinkedTreeMap_Node_initWithComGoogleGsonInternalLinkedTreeMap_Node_withId_withComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(nearest, key, header, ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(header))->prev_);
    if (comparison < 0) {
      nearest->left_ = created;
    }
    else {
      nearest->right_ = created;
    }
    ComGoogleGsonInternalLinkedTreeMap_rebalanceWithComGoogleGsonInternalLinkedTreeMap_Node_withBoolean_(self, nearest, YES);
  }
  size__++;
  modCount_++;
  return created;
}

- (ComGoogleGsonInternalLinkedTreeMap_Node *)findByObjectWithId:(id)key {
  @try {
    return key != nil ? [self findWithId:(id) key withBoolean:NO] : nil;
  }
  @catch (JavaLangClassCastException *e) {
    return nil;
  }
}

- (ComGoogleGsonInternalLinkedTreeMap_Node *)findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)entry_ {
  ComGoogleGsonInternalLinkedTreeMap_Node *mine = [self findByObjectWithId:[((id<JavaUtilMap_Entry>) nil_chk(entry_)) getKey]];
  jboolean valuesEqual = mine != nil && ComGoogleGsonInternalLinkedTreeMap_equalWithId_withId_(self, mine->value_, [entry_ getValue]);
  return valuesEqual ? mine : nil;
}

- (jboolean)equalWithId:(id)a
                 withId:(id)b {
  return ComGoogleGsonInternalLinkedTreeMap_equalWithId_withId_(self, a, b);
}

- (void)removeInternalWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)node
                                                      withBoolean:(jboolean)unlink {
  if (unlink) {
    ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(node))->prev_))->next_ = node->next_;
    ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(node->next_))->prev_ = node->prev_;
  }
  ComGoogleGsonInternalLinkedTreeMap_Node *left = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(node))->left_;
  ComGoogleGsonInternalLinkedTreeMap_Node *right = node->right_;
  ComGoogleGsonInternalLinkedTreeMap_Node *originalParent = node->parent_;
  if (left != nil && right != nil) {
    ComGoogleGsonInternalLinkedTreeMap_Node *adjacent = (left->height_ > right->height_) ? [left last] : [right first];
    [self removeInternalWithComGoogleGsonInternalLinkedTreeMap_Node:adjacent withBoolean:NO];
    jint leftHeight = 0;
    left = node->left_;
    if (left != nil) {
      leftHeight = left->height_;
      adjacent->left_ = left;
      left->parent_ = adjacent;
      node->left_ = nil;
    }
    jint rightHeight = 0;
    right = node->right_;
    if (right != nil) {
      rightHeight = right->height_;
      adjacent->right_ = right;
      right->parent_ = adjacent;
      node->right_ = nil;
    }
    adjacent->height_ = JavaLangMath_maxWithInt_withInt_(leftHeight, rightHeight) + 1;
    ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, node, adjacent);
    return;
  }
  else if (left != nil) {
    ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, node, left);
    node->left_ = nil;
  }
  else if (right != nil) {
    ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, node, right);
    node->right_ = nil;
  }
  else {
    ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, node, nil);
  }
  ComGoogleGsonInternalLinkedTreeMap_rebalanceWithComGoogleGsonInternalLinkedTreeMap_Node_withBoolean_(self, originalParent, NO);
  size__--;
  modCount_++;
}

- (ComGoogleGsonInternalLinkedTreeMap_Node *)removeInternalByKeyWithId:(id)key {
  ComGoogleGsonInternalLinkedTreeMap_Node *node = [self findByObjectWithId:key];
  if (node != nil) {
    [self removeInternalWithComGoogleGsonInternalLinkedTreeMap_Node:node withBoolean:YES];
  }
  return node;
}

- (void)replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)node
                       withComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)replacement {
  ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, node, replacement);
}

- (void)rebalanceWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)unbalanced
                                                 withBoolean:(jboolean)insert {
  ComGoogleGsonInternalLinkedTreeMap_rebalanceWithComGoogleGsonInternalLinkedTreeMap_Node_withBoolean_(self, unbalanced, insert);
}

- (void)rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)root {
  ComGoogleGsonInternalLinkedTreeMap_rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node_(self, root);
}

- (void)rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)root {
  ComGoogleGsonInternalLinkedTreeMap_rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node_(self, root);
}

- (id<JavaUtilSet>)entrySet {
  ComGoogleGsonInternalLinkedTreeMap_EntrySet *result = entrySet__;
  return result != nil ? result : (entrySet__ = new_ComGoogleGsonInternalLinkedTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedTreeMap_(self));
}

- (id<JavaUtilSet>)keySet {
  ComGoogleGsonInternalLinkedTreeMap_KeySet *result = keySet_LinkedTreeMap_;
  return result != nil ? result : (keySet_LinkedTreeMap_ = new_ComGoogleGsonInternalLinkedTreeMap_KeySet_initWithComGoogleGsonInternalLinkedTreeMap_(self));
}

- (id)writeReplace {
  return new_JavaUtilLinkedHashMap_initWithJavaUtilMap_(self);
}

+ (void)initialize {
  if (self == [ComGoogleGsonInternalLinkedTreeMap class]) {
    ComGoogleGsonInternalLinkedTreeMap_NATURAL_ORDER_ = new_ComGoogleGsonInternalLinkedTreeMap_$1_init();
    J2OBJC_SET_INITIALIZED(ComGoogleGsonInternalLinkedTreeMap)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "LinkedTreeMap", NULL, 0x1, NULL, NULL },
    { "initWithJavaUtilComparator:", "LinkedTreeMap", NULL, 0x1, NULL, NULL },
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "getWithId:", "get", "TV;", 0x1, NULL, "(Ljava/lang/Object;)TV;" },
    { "containsKeyWithId:", "containsKey", "Z", 0x1, NULL, NULL },
    { "putWithId:withId:", "put", "TV;", 0x1, NULL, "(TK;TV;)TV;" },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "TV;", 0x1, NULL, "(Ljava/lang/Object;)TV;" },
    { "findWithId:withBoolean:", "find", "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x0, NULL, "(TK;Z)Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;" },
    { "findByObjectWithId:", "findByObject", "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x0, NULL, NULL },
    { "findByEntryWithJavaUtilMap_Entry:", "findByEntry", "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x0, NULL, NULL },
    { "equalWithId:withId:", "equal", "Z", 0x2, NULL, NULL },
    { "removeInternalWithComGoogleGsonInternalLinkedTreeMap_Node:withBoolean:", "removeInternal", "V", 0x0, NULL, NULL },
    { "removeInternalByKeyWithId:", "removeInternalByKey", "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x0, NULL, NULL },
    { "replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node:withComGoogleGsonInternalLinkedTreeMap_Node:", "replaceInParent", "V", 0x2, NULL, NULL },
    { "rebalanceWithComGoogleGsonInternalLinkedTreeMap_Node:withBoolean:", "rebalance", "V", 0x2, NULL, NULL },
    { "rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node:", "rotateLeft", "V", 0x2, NULL, NULL },
    { "rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node:", "rotateRight", "V", 0x2, NULL, NULL },
    { "entrySet", NULL, "Ljava.util.Set;", 0x1, NULL, NULL },
    { "keySet", NULL, "Ljava.util.Set;", 0x1, NULL, NULL },
    { "writeReplace", NULL, "Ljava.lang.Object;", 0x2, "Ljava.io.ObjectStreamException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NATURAL_ORDER_", NULL, 0x1a, "Ljava.util.Comparator;", &ComGoogleGsonInternalLinkedTreeMap_NATURAL_ORDER_, "Ljava/util/Comparator<Ljava/lang/Comparable;>;",  },
    { "comparator_", NULL, 0x0, "Ljava.util.Comparator;", NULL, "Ljava/util/Comparator<-TK;>;",  },
    { "root_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "size__", "size", 0x0, "I", NULL, NULL,  },
    { "modCount_", NULL, 0x0, "I", NULL, NULL,  },
    { "header_", NULL, 0x10, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "entrySet__", "entrySet", 0x2, "Lcom.google.gson.internal.LinkedTreeMap$EntrySet;", NULL, NULL,  },
    { "keySet_LinkedTreeMap_", "keySet", 0x2, "Lcom.google.gson.internal.LinkedTreeMap$KeySet;", NULL, NULL,  },
  };
  static const char *superclass_type_args[] = {"TK;", "TV;"};
  static const char *inner_classes[] = {"Lcom.google.gson.internal.LinkedTreeMap$Node;", "Lcom.google.gson.internal.LinkedTreeMap$LinkedTreeMapIterator;", "Lcom.google.gson.internal.LinkedTreeMap$EntrySet;", "Lcom.google.gson.internal.LinkedTreeMap$KeySet;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedTreeMap = { 2, "LinkedTreeMap", "com.google.gson.internal", NULL, 0x11, 21, methods, 8, fields, 2, superclass_type_args, 4, inner_classes, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/util/AbstractMap<TK;TV;>;Ljava/io/Serializable;" };
  return &_ComGoogleGsonInternalLinkedTreeMap;
}

@end

void ComGoogleGsonInternalLinkedTreeMap_init(ComGoogleGsonInternalLinkedTreeMap *self) {
  (void) ComGoogleGsonInternalLinkedTreeMap_initWithJavaUtilComparator_(self, (id<JavaUtilComparator>) check_protocol_cast(ComGoogleGsonInternalLinkedTreeMap_NATURAL_ORDER_, @protocol(JavaUtilComparator)));
}

ComGoogleGsonInternalLinkedTreeMap *new_ComGoogleGsonInternalLinkedTreeMap_init() {
  ComGoogleGsonInternalLinkedTreeMap *self = [ComGoogleGsonInternalLinkedTreeMap alloc];
  ComGoogleGsonInternalLinkedTreeMap_init(self);
  return self;
}

void ComGoogleGsonInternalLinkedTreeMap_initWithJavaUtilComparator_(ComGoogleGsonInternalLinkedTreeMap *self, id<JavaUtilComparator> comparator) {
  (void) JavaUtilAbstractMap_init(self);
  self->size__ = 0;
  self->modCount_ = 0;
  self->header_ = new_ComGoogleGsonInternalLinkedTreeMap_Node_init();
  self->comparator_ = comparator != nil ? ((id) comparator) : ((id) ComGoogleGsonInternalLinkedTreeMap_NATURAL_ORDER_);
}

ComGoogleGsonInternalLinkedTreeMap *new_ComGoogleGsonInternalLinkedTreeMap_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) {
  ComGoogleGsonInternalLinkedTreeMap *self = [ComGoogleGsonInternalLinkedTreeMap alloc];
  ComGoogleGsonInternalLinkedTreeMap_initWithJavaUtilComparator_(self, comparator);
  return self;
}

jboolean ComGoogleGsonInternalLinkedTreeMap_equalWithId_withId_(ComGoogleGsonInternalLinkedTreeMap *self, id a, id b) {
  return a == b || (a != nil && [a isEqual:b]);
}

void ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(ComGoogleGsonInternalLinkedTreeMap *self, ComGoogleGsonInternalLinkedTreeMap_Node *node, ComGoogleGsonInternalLinkedTreeMap_Node *replacement) {
  ComGoogleGsonInternalLinkedTreeMap_Node *parent = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(node))->parent_;
  node->parent_ = nil;
  if (replacement != nil) {
    replacement->parent_ = parent;
  }
  if (parent != nil) {
    if (parent->left_ == node) {
      parent->left_ = replacement;
    }
    else {
      NSCAssert(parent->right_ == node, @"com/google/gson/internal/LinkedTreeMap.java:295 condition failed: assert (parent.right == node);");
      parent->right_ = replacement;
    }
  }
  else {
    self->root_ = replacement;
  }
}

void ComGoogleGsonInternalLinkedTreeMap_rebalanceWithComGoogleGsonInternalLinkedTreeMap_Node_withBoolean_(ComGoogleGsonInternalLinkedTreeMap *self, ComGoogleGsonInternalLinkedTreeMap_Node *unbalanced, jboolean insert) {
  for (ComGoogleGsonInternalLinkedTreeMap_Node *node = unbalanced; node != nil; node = node->parent_) {
    ComGoogleGsonInternalLinkedTreeMap_Node *left = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(node))->left_;
    ComGoogleGsonInternalLinkedTreeMap_Node *right = node->right_;
    jint leftHeight = left != nil ? left->height_ : 0;
    jint rightHeight = right != nil ? right->height_ : 0;
    jint delta = leftHeight - rightHeight;
    if (delta == -2) {
      ComGoogleGsonInternalLinkedTreeMap_Node *rightLeft = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(right))->left_;
      ComGoogleGsonInternalLinkedTreeMap_Node *rightRight = right->right_;
      jint rightRightHeight = rightRight != nil ? rightRight->height_ : 0;
      jint rightLeftHeight = rightLeft != nil ? rightLeft->height_ : 0;
      jint rightDelta = rightLeftHeight - rightRightHeight;
      if (rightDelta == -1 || (rightDelta == 0 && !insert)) {
        ComGoogleGsonInternalLinkedTreeMap_rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node_(self, node);
      }
      else {
        NSCAssert(rightDelta == 1, @"com/google/gson/internal/LinkedTreeMap.java:328 condition failed: assert (rightDelta == 1);");
        ComGoogleGsonInternalLinkedTreeMap_rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node_(self, right);
        ComGoogleGsonInternalLinkedTreeMap_rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node_(self, node);
      }
      if (insert) {
        break;
      }
    }
    else if (delta == 2) {
      ComGoogleGsonInternalLinkedTreeMap_Node *leftLeft = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(left))->left_;
      ComGoogleGsonInternalLinkedTreeMap_Node *leftRight = left->right_;
      jint leftRightHeight = leftRight != nil ? leftRight->height_ : 0;
      jint leftLeftHeight = leftLeft != nil ? leftLeft->height_ : 0;
      jint leftDelta = leftLeftHeight - leftRightHeight;
      if (leftDelta == 1 || (leftDelta == 0 && !insert)) {
        ComGoogleGsonInternalLinkedTreeMap_rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node_(self, node);
      }
      else {
        NSCAssert(leftDelta == -1, @"com/google/gson/internal/LinkedTreeMap.java:346 condition failed: assert (leftDelta == -1);");
        ComGoogleGsonInternalLinkedTreeMap_rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node_(self, left);
        ComGoogleGsonInternalLinkedTreeMap_rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node_(self, node);
      }
      if (insert) {
        break;
      }
    }
    else if (delta == 0) {
      node->height_ = leftHeight + 1;
      if (insert) {
        break;
      }
    }
    else {
      NSCAssert((delta == -1 || delta == 1), @"com/google/gson/internal/LinkedTreeMap.java:361 condition failed: assert (delta == -1 || delta == 1);");
      node->height_ = JavaLangMath_maxWithInt_withInt_(leftHeight, rightHeight) + 1;
      if (!insert) {
        break;
      }
    }
  }
}

void ComGoogleGsonInternalLinkedTreeMap_rotateLeftWithComGoogleGsonInternalLinkedTreeMap_Node_(ComGoogleGsonInternalLinkedTreeMap *self, ComGoogleGsonInternalLinkedTreeMap_Node *root) {
  ComGoogleGsonInternalLinkedTreeMap_Node *left = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(root))->left_;
  ComGoogleGsonInternalLinkedTreeMap_Node *pivot = root->right_;
  ComGoogleGsonInternalLinkedTreeMap_Node *pivotLeft = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(pivot))->left_;
  ComGoogleGsonInternalLinkedTreeMap_Node *pivotRight = pivot->right_;
  root->right_ = pivotLeft;
  if (pivotLeft != nil) {
    pivotLeft->parent_ = root;
  }
  ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, root, pivot);
  pivot->left_ = root;
  root->parent_ = pivot;
  root->height_ = JavaLangMath_maxWithInt_withInt_(left != nil ? left->height_ : 0, pivotLeft != nil ? pivotLeft->height_ : 0) + 1;
  pivot->height_ = JavaLangMath_maxWithInt_withInt_(root->height_, pivotRight != nil ? pivotRight->height_ : 0) + 1;
}

void ComGoogleGsonInternalLinkedTreeMap_rotateRightWithComGoogleGsonInternalLinkedTreeMap_Node_(ComGoogleGsonInternalLinkedTreeMap *self, ComGoogleGsonInternalLinkedTreeMap_Node *root) {
  ComGoogleGsonInternalLinkedTreeMap_Node *pivot = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(root))->left_;
  ComGoogleGsonInternalLinkedTreeMap_Node *right = root->right_;
  ComGoogleGsonInternalLinkedTreeMap_Node *pivotLeft = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(pivot))->left_;
  ComGoogleGsonInternalLinkedTreeMap_Node *pivotRight = pivot->right_;
  root->left_ = pivotRight;
  if (pivotRight != nil) {
    pivotRight->parent_ = root;
  }
  ComGoogleGsonInternalLinkedTreeMap_replaceInParentWithComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, root, pivot);
  pivot->right_ = root;
  root->parent_ = pivot;
  root->height_ = JavaLangMath_maxWithInt_withInt_(right != nil ? right->height_ : 0, pivotRight != nil ? pivotRight->height_ : 0) + 1;
  pivot->height_ = JavaLangMath_maxWithInt_withInt_(root->height_, pivotLeft != nil ? pivotLeft->height_ : 0) + 1;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedTreeMap)

@implementation ComGoogleGsonInternalLinkedTreeMap_Node

- (instancetype)init {
  ComGoogleGsonInternalLinkedTreeMap_Node_init(self);
  return self;
}

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)parent
                                                         withId:(id)key
                    withComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)next
                    withComGoogleGsonInternalLinkedTreeMap_Node:(ComGoogleGsonInternalLinkedTreeMap_Node *)prev {
  ComGoogleGsonInternalLinkedTreeMap_Node_initWithComGoogleGsonInternalLinkedTreeMap_Node_withId_withComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, parent, key, next, prev);
  return self;
}

- (id)getKey {
  return key_;
}

- (id)getValue {
  return value_;
}

- (id)setValueWithId:(id)value {
  id oldValue = self->value_;
  self->value_ = value;
  return oldValue;
}

- (jboolean)isEqual:(id)o {
  if ([JavaUtilMap_Entry_class_() isInstance:o]) {
    id<JavaUtilMap_Entry> other = (id<JavaUtilMap_Entry>) check_protocol_cast(o, @protocol(JavaUtilMap_Entry));
    return (key_ == nil ? [((id<JavaUtilMap_Entry>) nil_chk(other)) getKey] == nil : [key_ isEqual:[((id<JavaUtilMap_Entry>) nil_chk(other)) getKey]]) && (value_ == nil ? [other getValue] == nil : [value_ isEqual:[other getValue]]);
  }
  return NO;
}

- (NSUInteger)hash {
  return (key_ == nil ? 0 : ((jint) [key_ hash])) ^ (value_ == nil ? 0 : ((jint) [value_ hash]));
}

- (NSString *)description {
  return JreStrcat("@C@", key_, '=', value_);
}

- (ComGoogleGsonInternalLinkedTreeMap_Node *)first {
  ComGoogleGsonInternalLinkedTreeMap_Node *node = self;
  ComGoogleGsonInternalLinkedTreeMap_Node *child = node->left_;
  while (child != nil) {
    node = child;
    child = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(node))->left_;
  }
  return node;
}

- (ComGoogleGsonInternalLinkedTreeMap_Node *)last {
  ComGoogleGsonInternalLinkedTreeMap_Node *node = self;
  ComGoogleGsonInternalLinkedTreeMap_Node *child = node->right_;
  while (child != nil) {
    node = child;
    child = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(node))->right_;
  }
  return node;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Node", NULL, 0x0, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedTreeMap_Node:withId:withComGoogleGsonInternalLinkedTreeMap_Node:withComGoogleGsonInternalLinkedTreeMap_Node:", "Node", NULL, 0x0, NULL, "(Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;TK;Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;)V" },
    { "getKey", NULL, "TK;", 0x1, NULL, "()TK;" },
    { "getValue", NULL, "TV;", 0x1, NULL, "()TV;" },
    { "setValueWithId:", "setValue", "TV;", 0x1, NULL, "(TV;)TV;" },
    { "isEqual:", "equals", "Z", 0x1, NULL, NULL },
    { "hash", "hashCode", "I", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "first", NULL, "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x1, NULL, NULL },
    { "last", NULL, "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "parent_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "left_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "right_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "next_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "prev_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "key_", NULL, 0x10, "TK;", NULL, "TK;",  },
    { "value_", NULL, 0x0, "TV;", NULL, "TV;",  },
    { "height_", NULL, 0x0, "I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedTreeMap_Node = { 2, "Node", "com.google.gson.internal", "LinkedTreeMap", 0x18, 10, methods, 8, fields, 0, NULL, 0, NULL, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/Map$Entry<TK;TV;>;" };
  return &_ComGoogleGsonInternalLinkedTreeMap_Node;
}

@end

void ComGoogleGsonInternalLinkedTreeMap_Node_init(ComGoogleGsonInternalLinkedTreeMap_Node *self) {
  (void) NSObject_init(self);
  self->key_ = nil;
  self->next_ = self->prev_ = self;
}

ComGoogleGsonInternalLinkedTreeMap_Node *new_ComGoogleGsonInternalLinkedTreeMap_Node_init() {
  ComGoogleGsonInternalLinkedTreeMap_Node *self = [ComGoogleGsonInternalLinkedTreeMap_Node alloc];
  ComGoogleGsonInternalLinkedTreeMap_Node_init(self);
  return self;
}

void ComGoogleGsonInternalLinkedTreeMap_Node_initWithComGoogleGsonInternalLinkedTreeMap_Node_withId_withComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(ComGoogleGsonInternalLinkedTreeMap_Node *self, ComGoogleGsonInternalLinkedTreeMap_Node *parent, id key, ComGoogleGsonInternalLinkedTreeMap_Node *next, ComGoogleGsonInternalLinkedTreeMap_Node *prev) {
  (void) NSObject_init(self);
  self->parent_ = parent;
  self->key_ = key;
  self->height_ = 1;
  self->next_ = next;
  self->prev_ = prev;
  ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(prev))->next_ = self;
  ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(next))->prev_ = self;
}

ComGoogleGsonInternalLinkedTreeMap_Node *new_ComGoogleGsonInternalLinkedTreeMap_Node_initWithComGoogleGsonInternalLinkedTreeMap_Node_withId_withComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(ComGoogleGsonInternalLinkedTreeMap_Node *parent, id key, ComGoogleGsonInternalLinkedTreeMap_Node *next, ComGoogleGsonInternalLinkedTreeMap_Node *prev) {
  ComGoogleGsonInternalLinkedTreeMap_Node *self = [ComGoogleGsonInternalLinkedTreeMap_Node alloc];
  ComGoogleGsonInternalLinkedTreeMap_Node_initWithComGoogleGsonInternalLinkedTreeMap_Node_withId_withComGoogleGsonInternalLinkedTreeMap_Node_withComGoogleGsonInternalLinkedTreeMap_Node_(self, parent, key, next, prev);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedTreeMap_Node)

@implementation ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator

- (jboolean)hasNext {
  return next_ != this$0_->header_;
}

- (ComGoogleGsonInternalLinkedTreeMap_Node *)nextNode {
  return ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(self);
}

- (void)remove {
  if (lastReturned_ == nil) {
    @throw new_JavaLangIllegalStateException_init();
  }
  [this$0_ removeInternalWithComGoogleGsonInternalLinkedTreeMap_Node:lastReturned_ withBoolean:YES];
  lastReturned_ = nil;
  expectedModCount_ = this$0_->modCount_;
}

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap:(ComGoogleGsonInternalLinkedTreeMap *)outer$ {
  ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedTreeMap_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "hasNext", NULL, "Z", 0x11, NULL, NULL },
    { "nextNode", NULL, "Lcom.google.gson.internal.LinkedTreeMap$Node;", 0x10, NULL, NULL },
    { "remove", NULL, "V", 0x11, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedTreeMap:", "init", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedTreeMap;", NULL, NULL,  },
    { "next_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "lastReturned_", NULL, 0x0, "Lcom.google.gson.internal.LinkedTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedTreeMap$Node<TK;TV;>;",  },
    { "expectedModCount_", NULL, 0x0, "I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator = { 2, "LinkedTreeMapIterator", "com.google.gson.internal", "LinkedTreeMap", 0x402, 4, methods, 4, fields, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/Iterator<TT;>;" };
  return &_ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator;
}

@end

ComGoogleGsonInternalLinkedTreeMap_Node *ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator *self) {
  ComGoogleGsonInternalLinkedTreeMap_Node *e = self->next_;
  if (e == self->this$0_->header_) {
    @throw new_JavaUtilNoSuchElementException_init();
  }
  if (self->this$0_->modCount_ != self->expectedModCount_) {
    @throw new_JavaUtilConcurrentModificationException_init();
  }
  self->next_ = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(e))->next_;
  return self->lastReturned_ = e;
}

void ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedTreeMap_(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator *self, ComGoogleGsonInternalLinkedTreeMap *outer$) {
  self->this$0_ = outer$;
  (void) NSObject_init(self);
  self->next_ = ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(outer$->header_))->next_;
  self->lastReturned_ = nil;
  self->expectedModCount_ = outer$->modCount_;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator)

@implementation ComGoogleGsonInternalLinkedTreeMap_EntrySet

- (jint)size {
  return this$0_->size__;
}

- (id<JavaUtilIterator>)iterator {
  return new_ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_EntrySet_(self);
}

- (jboolean)containsWithId:(id)o {
  return [JavaUtilMap_Entry_class_() isInstance:o] && [this$0_ findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>) check_protocol_cast(o, @protocol(JavaUtilMap_Entry))] != nil;
}

- (jboolean)removeWithId:(id)o {
  if (!([JavaUtilMap_Entry_class_() isInstance:o])) {
    return NO;
  }
  ComGoogleGsonInternalLinkedTreeMap_Node *node = [this$0_ findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>) check_protocol_cast(o, @protocol(JavaUtilMap_Entry))];
  if (node == nil) {
    return NO;
  }
  [this$0_ removeInternalWithComGoogleGsonInternalLinkedTreeMap_Node:node withBoolean:YES];
  return YES;
}

- (void)clear {
  [this$0_ clear];
}

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap:(ComGoogleGsonInternalLinkedTreeMap *)outer$ {
  ComGoogleGsonInternalLinkedTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedTreeMap_(self, outer$);
  return self;
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "iterator", NULL, "Ljava.util.Iterator;", 0x1, NULL, NULL },
    { "containsWithId:", "contains", "Z", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "Z", 0x1, NULL, NULL },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedTreeMap:", "init", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedTreeMap;", NULL, NULL,  },
  };
  static const char *superclass_type_args[] = {"Ljava.util.Map$Entry;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedTreeMap_EntrySet = { 2, "EntrySet", "com.google.gson.internal", "LinkedTreeMap", 0x0, 6, methods, 1, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/util/AbstractSet<Ljava/util/Map$Entry<TK;TV;>;>;" };
  return &_ComGoogleGsonInternalLinkedTreeMap_EntrySet;
}

@end

void ComGoogleGsonInternalLinkedTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedTreeMap_(ComGoogleGsonInternalLinkedTreeMap_EntrySet *self, ComGoogleGsonInternalLinkedTreeMap *outer$) {
  self->this$0_ = outer$;
  (void) JavaUtilAbstractSet_init(self);
}

ComGoogleGsonInternalLinkedTreeMap_EntrySet *new_ComGoogleGsonInternalLinkedTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedTreeMap_(ComGoogleGsonInternalLinkedTreeMap *outer$) {
  ComGoogleGsonInternalLinkedTreeMap_EntrySet *self = [ComGoogleGsonInternalLinkedTreeMap_EntrySet alloc];
  ComGoogleGsonInternalLinkedTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedTreeMap_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedTreeMap_EntrySet)

@implementation ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1

- (id<JavaUtilMap_Entry>)next {
  return ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(self);
}

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap_EntrySet:(ComGoogleGsonInternalLinkedTreeMap_EntrySet *)outer$ {
  ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_EntrySet_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "Ljava.util.Map$Entry;", 0x1, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedTreeMap_EntrySet:", "", NULL, 0x0, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.util.Map$Entry;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonInternalLinkedTreeMap_EntrySet", "iterator" };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1 = { 2, "", "com.google.gson.internal", "LinkedTreeMap$EntrySet", 0x8008, 2, methods, 0, NULL, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/internal/LinkedTreeMap$LinkedTreeMapIterator<Ljava/util/Map$Entry<TK;TV;>;>;" };
  return &_ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1;
}

@end

void ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_EntrySet_(ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1 *self, ComGoogleGsonInternalLinkedTreeMap_EntrySet *outer$) {
  (void) ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedTreeMap_(self, outer$->this$0_);
}

ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1 *new_ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_EntrySet_(ComGoogleGsonInternalLinkedTreeMap_EntrySet *outer$) {
  ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1 *self = [ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1 alloc];
  ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_EntrySet_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedTreeMap_EntrySet_$1)

@implementation ComGoogleGsonInternalLinkedTreeMap_KeySet

- (jint)size {
  return this$0_->size__;
}

- (id<JavaUtilIterator>)iterator {
  return new_ComGoogleGsonInternalLinkedTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_KeySet_(self);
}

- (jboolean)containsWithId:(id)o {
  return [this$0_ containsKeyWithId:o];
}

- (jboolean)removeWithId:(id)key {
  return [this$0_ removeInternalByKeyWithId:key] != nil;
}

- (void)clear {
  [this$0_ clear];
}

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap:(ComGoogleGsonInternalLinkedTreeMap *)outer$ {
  ComGoogleGsonInternalLinkedTreeMap_KeySet_initWithComGoogleGsonInternalLinkedTreeMap_(self, outer$);
  return self;
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "iterator", NULL, "Ljava.util.Iterator;", 0x1, NULL, NULL },
    { "containsWithId:", "contains", "Z", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "Z", 0x1, NULL, NULL },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedTreeMap:", "init", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedTreeMap;", NULL, NULL,  },
  };
  static const char *superclass_type_args[] = {"TK;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedTreeMap_KeySet = { 2, "KeySet", "com.google.gson.internal", "LinkedTreeMap", 0x10, 6, methods, 1, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/util/AbstractSet<TK;>;" };
  return &_ComGoogleGsonInternalLinkedTreeMap_KeySet;
}

@end

void ComGoogleGsonInternalLinkedTreeMap_KeySet_initWithComGoogleGsonInternalLinkedTreeMap_(ComGoogleGsonInternalLinkedTreeMap_KeySet *self, ComGoogleGsonInternalLinkedTreeMap *outer$) {
  self->this$0_ = outer$;
  (void) JavaUtilAbstractSet_init(self);
}

ComGoogleGsonInternalLinkedTreeMap_KeySet *new_ComGoogleGsonInternalLinkedTreeMap_KeySet_initWithComGoogleGsonInternalLinkedTreeMap_(ComGoogleGsonInternalLinkedTreeMap *outer$) {
  ComGoogleGsonInternalLinkedTreeMap_KeySet *self = [ComGoogleGsonInternalLinkedTreeMap_KeySet alloc];
  ComGoogleGsonInternalLinkedTreeMap_KeySet_initWithComGoogleGsonInternalLinkedTreeMap_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedTreeMap_KeySet)

@implementation ComGoogleGsonInternalLinkedTreeMap_KeySet_$1

- (id)next {
  return ((ComGoogleGsonInternalLinkedTreeMap_Node *) nil_chk(ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_nextNode(self)))->key_;
}

- (instancetype)initWithComGoogleGsonInternalLinkedTreeMap_KeySet:(ComGoogleGsonInternalLinkedTreeMap_KeySet *)outer$ {
  ComGoogleGsonInternalLinkedTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_KeySet_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "TK;", 0x1, NULL, "()TK;" },
    { "initWithComGoogleGsonInternalLinkedTreeMap_KeySet:", "", NULL, 0x0, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"TK;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonInternalLinkedTreeMap_KeySet", "iterator" };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedTreeMap_KeySet_$1 = { 2, "", "com.google.gson.internal", "LinkedTreeMap$KeySet", 0x8008, 2, methods, 0, NULL, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/internal/LinkedTreeMap$LinkedTreeMapIterator<TK;>;" };
  return &_ComGoogleGsonInternalLinkedTreeMap_KeySet_$1;
}

@end

void ComGoogleGsonInternalLinkedTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_KeySet_(ComGoogleGsonInternalLinkedTreeMap_KeySet_$1 *self, ComGoogleGsonInternalLinkedTreeMap_KeySet *outer$) {
  (void) ComGoogleGsonInternalLinkedTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedTreeMap_(self, outer$->this$0_);
}

ComGoogleGsonInternalLinkedTreeMap_KeySet_$1 *new_ComGoogleGsonInternalLinkedTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_KeySet_(ComGoogleGsonInternalLinkedTreeMap_KeySet *outer$) {
  ComGoogleGsonInternalLinkedTreeMap_KeySet_$1 *self = [ComGoogleGsonInternalLinkedTreeMap_KeySet_$1 alloc];
  ComGoogleGsonInternalLinkedTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedTreeMap_KeySet_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedTreeMap_KeySet_$1)

@implementation ComGoogleGsonInternalLinkedTreeMap_$1

- (jint)compareWithId:(id<JavaLangComparable>)a
               withId:(id<JavaLangComparable>)b {
  return [((id<JavaLangComparable>) nil_chk(a)) compareToWithId:b];
}

- (instancetype)init {
  ComGoogleGsonInternalLinkedTreeMap_$1_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "compareWithId:withId:", "compare", "I", 0x1, NULL, NULL },
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedTreeMap_$1 = { 2, "", "com.google.gson.internal", "LinkedTreeMap", 0x8008, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "Ljava/lang/Object;Ljava/util/Comparator<Ljava/lang/Comparable;>;" };
  return &_ComGoogleGsonInternalLinkedTreeMap_$1;
}

@end

void ComGoogleGsonInternalLinkedTreeMap_$1_init(ComGoogleGsonInternalLinkedTreeMap_$1 *self) {
  (void) NSObject_init(self);
}

ComGoogleGsonInternalLinkedTreeMap_$1 *new_ComGoogleGsonInternalLinkedTreeMap_$1_init() {
  ComGoogleGsonInternalLinkedTreeMap_$1 *self = [ComGoogleGsonInternalLinkedTreeMap_$1 alloc];
  ComGoogleGsonInternalLinkedTreeMap_$1_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedTreeMap_$1)
