//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/internal/ObjectConstructor.java
//

#ifndef _ComGoogleGsonInternalObjectConstructor_H_
#define _ComGoogleGsonInternalObjectConstructor_H_

#include "J2ObjC_header.h"

@protocol ComGoogleGsonInternalObjectConstructor < NSObject, JavaObject >

- (id)construct;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalObjectConstructor)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalObjectConstructor)

#endif // _ComGoogleGsonInternalObjectConstructor_H_
