//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:/Users/tway/dev/FeedRead/core/libs/gson-2.3.1-sources.jar!com/google/gson/internal/Streams.java
//

#ifndef _ComGoogleGsonInternalStreams_H_
#define _ComGoogleGsonInternalStreams_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoWriter;
@protocol JavaLangAppendable;

@interface ComGoogleGsonInternalStreams : NSObject

#pragma mark Public

- (instancetype)init;

+ (ComGoogleGsonJsonElement *)parseWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader;

+ (void)writeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)element
        withComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)writer;

+ (JavaIoWriter *)writerForAppendableWithJavaLangAppendable:(id<JavaLangAppendable>)appendable;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalStreams)

FOUNDATION_EXPORT ComGoogleGsonJsonElement *ComGoogleGsonInternalStreams_parseWithComGoogleGsonStreamJsonReader_(ComGoogleGsonStreamJsonReader *reader);

FOUNDATION_EXPORT void ComGoogleGsonInternalStreams_writeWithComGoogleGsonJsonElement_withComGoogleGsonStreamJsonWriter_(ComGoogleGsonJsonElement *element, ComGoogleGsonStreamJsonWriter *writer);

FOUNDATION_EXPORT JavaIoWriter *ComGoogleGsonInternalStreams_writerForAppendableWithJavaLangAppendable_(id<JavaLangAppendable> appendable);

FOUNDATION_EXPORT void ComGoogleGsonInternalStreams_init(ComGoogleGsonInternalStreams *self);

FOUNDATION_EXPORT ComGoogleGsonInternalStreams *new_ComGoogleGsonInternalStreams_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalStreams)

#endif // _ComGoogleGsonInternalStreams_H_
